// Curated ecosystem-scene catalog. This data is intentionally independent from
// representative dinosaur cards: every scene remains in a separate review lane.
window.ecosystemSceneCatalog = {
  schemaVersion: 1,
  generatedAt: "2026-08-03T02:30:00.000Z",
  policy: {
    targetAudience: "ages 5-14",
    representativePromotion: "prohibited; ecosystem scenes are never representative-card candidates",
    evidenceBoundary: "Formation overlap or fossil association does not by itself prove the exact meeting, pose, weather, pursuit, herd, or event shown.",
    publicationRule: "A scene may be published only when anatomy, ecology, and responsive gates are supported.",
    compositionDiversityRule: "Every scene requires a unique composition key and a distinct camera-plus-spatial-layout signature.",
  },
  sceneTypes: [
    { id: "coexistence", label: "공존" },
    { id: "predation-tension", label: "포식 긴장" },
    { id: "herd-growth", label: "무리·성장" },
    { id: "environment-event", label: "환경·사건" },
  ],
  timeBins: [
    {
      id: "late-triassic",
      label: "후기 트라이아스기",
      era: "triassic",
      ageRangeMa: { older: 237.0, younger: 201.4 },
      sceneIds: ["eoraptor-herrerasaurus-cancha-de-bochas"],
    },
    {
      id: "early-jurassic",
      label: "전기 쥐라기",
      era: "jurassic",
      ageRangeMa: { older: 201.4, younger: 174.7 },
      sceneIds: ["scutellosaurus-dilophosaurus-kayenta"],
    },
    {
      id: "middle-jurassic",
      label: "중기 쥐라기",
      era: "jurassic",
      ageRangeMa: { older: 174.7, younger: 161.5 },
      sceneIds: [],
    },
    {
      id: "late-jurassic",
      label: "후기 쥐라기",
      era: "jurassic",
      ageRangeMa: { older: 161.5, younger: 143.1 },
      sceneIds: ["allosaurus-camarasaurus-morrison"],
    },
    {
      id: "early-cretaceous",
      label: "전기 백악기",
      era: "cretaceous",
      ageRangeMa: { older: 143.1, younger: 100.5 },
      sceneIds: ["yutyrannus-yixian-ash-channel"],
    },
    {
      id: "late-cretaceous",
      label: "후기 백악기",
      era: "cretaceous",
      ageRangeMa: { older: 100.5, younger: 66.0 },
      sceneIds: [
        "parasaurolophus-centrosaurus-lower-dinosaur-park",
        "velociraptor-protoceratops-djadokhta",
        "tarbosaurus-saurolophus-nemegt",
        "triceratops-edmontosaurus-lower-hell-creek",
        "tyrannosaurus-edmontosaurus-hell-creek",
      ],
    },
  ],
  scenes: [
    {
      id: "eoraptor-herrerasaurus-cancha-de-bochas",
      timeBinId: "late-triassic",
      sceneType: "coexistence",
      title: "동심원 지형을 사이에 둔 에오랍토르와 헤레라사우루스",
      summary: "같은 낮은 층준에서 보고된 두 종을 넓은 빈 땅과 반대 이동축으로 분리한 후기 트라이아스기 공존 복원입니다.",
      asset: {
        src: "assets/dinosaurs/eoraptor-lunensis-herrerasaurus-cancha-de-bochas-high-oblique-concentric-coexistence-imagegen-v1.png",
        width: 1122,
        height: 1402,
        bytes: 3476030,
        sha256: "3461013156e1b114398851e77c989a0a5d057b30b0e84784c7156db4dd219cb7",
        orientation: "portrait",
      },
      formation: {
        name: "Ischigualasto Formation, Cancha de Bochas Member",
        context: "lowermost Cancha de Bochas level and well-drained floodplain context; not literal fossil positions",
        ageRangeMa: { older: 233.0, younger: 225.0 },
        resolution: "same cited low member level; exact shared moment and spacing unresolved",
      },
      participants: [
        { taxonId: "eoraptor-lunensis", scientificName: "Eoraptor lunensis", role: "context", certainty: "same cited low member level: high" },
        { taxonId: "herrerasaurus-ischigualastensis", scientificName: "Herrerasaurus ischigualastensis", role: "focal", certainty: "same cited low member level: high" },
      ],
      compositionKey: "portrait-high-oblique-concentric-paleosol",
      compositionLabel: "고각도 동심원 지형 분리",
      composition: {
        key: "portrait-high-oblique-concentric-paleosol",
        label: "고각도 동심원 지형 분리",
        family: "radial-landform",
        orientation: "portrait",
        camera: "high diagonal near-top-down portrait field-observation view",
        spatialLayout: "small Eoraptor in the upper third and larger Herrerasaurus in the lower third, separated by concentric paleosol rings and opposing travel axes",
        diversityTags: ["high-oblique", "concentric-ground", "upper-lower-split", "opposed-directions"],
      },
      epistemic: {
        known: ["The cited study reports Eoraptor and Herrerasaurus from the same low level of the Cancha de Bochas Member."],
        reconstructed: ["Concentric paleosol rings, exact spacing, colors, weather, walking directions, and simultaneous presence are reconstructed."],
        boundary: "The scene communicates stratigraphic coexistence only and does not claim a meeting, pursuit, mutual awareness, or direct interaction.",
      },
      evidence: [
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3088398/", use: "same low member level and floodplain context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; two project-owned identity images used only as anatomy references; external research used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/triassic-concentric-ecosystem-scene-20260803.json#",
        promptRecord: "tools/comfyui/triassic-concentric-ecosystem-scene-20260803.json#prompt",
        prompt: "tools/comfyui/triassic-concentric-ecosystem-scene-20260803.json#prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image with two anatomy-only project references; first output passed ecosystem-scene review",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size ecosystem-scene pass; scene-scale digits remain lower-confidence and cannot support representative promotion." },
        ecology: { status: "supported", note: "Same cited low-member level is supported; exact meeting and behavior are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "scutellosaurus-dilophosaurus-kayenta",
      timeBinId: "early-jurassic",
      sceneType: "coexistence",
      title: "붉은 평원을 가로지르는 스쿠텔로사우루스와 딜로포사우루스",
      summary: "카옌타층 동물상 두 종을 화면 양끝과 서로 다른 깊이에 놓은 전기 쥐라기 지층 단위 공존 복원입니다.",
      asset: {
        src: "assets/dinosaurs/scutellosaurus-lawleri-dilophosaurus-kayenta-groundlevel-longlens-frieze-coexistence-imagegen-v1.png",
        width: 1672,
        height: 941,
        bytes: 2837221,
        sha256: "fe643e98e890b23d62ad97ec811935838372378df16ffdccc22bce58d00ceb29",
        orientation: "landscape",
      },
      formation: {
        name: "Kayenta Formation",
        context: "silty-facies fauna and red floodplain/dune-margin context; not one exact shared bed",
        ageRangeMa: { older: 199.3, younger: 182.7 },
        resolution: "formation/facies scale; exact horizon, encounter, and simultaneous presence unresolved",
      },
      participants: [
        { taxonId: "scutellosaurus-lawleri", scientificName: "Scutellosaurus lawleri", role: "context", certainty: "Kayenta silty-facies occurrence: high; exact shared bed: unresolved" },
        { taxonId: "dilophosaurus-wetherilli", scientificName: "Dilophosaurus wetherilli", role: "focal", certainty: "Kayenta occurrence: high; exact shared bed: unresolved" },
      ],
      compositionKey: "landscape-groundlevel-longlens-vertical-frieze",
      compositionLabel: "지면 높이 세 구역 프리즈",
      composition: {
        key: "landscape-groundlevel-longlens-vertical-frieze",
        label: "지면 높이 세 구역 프리즈",
        family: "transverse-frieze",
        orientation: "landscape",
        camera: "ground-height long-telephoto landscape view",
        spatialLayout: "Dilophosaurus occupies the far-left middle distance and Scutellosaurus the far-right near plane, facing outward across a broad empty center divided by vertical trunks",
        diversityTags: ["vertical-frieze", "long-lens", "edge-separated", "opposed-directions"],
      },
      epistemic: {
        known: ["Both named taxa are documented from the Kayenta Formation, with Scutellosaurus associated with its silty facies."],
        reconstructed: ["Exact co-presence, spacing, travel directions, colors, plants, dune margin, and weather are reconstructed."],
        boundary: "This is a formation-level fauna comparison and does not claim one shared bed, a real encounter, pursuit, or predator-prey behavior.",
      },
      evidence: [
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8292774/", use: "Scutellosaurus anatomy and Kayenta silty-facies context" },
        { url: "https://www.cambridge.org/core/journals/journal-of-paleontology/article/comprehensive-anatomical-and-phylogenetic-evaluation-of-dilophosaurus-wetherilli-dinosauria-theropoda-with-descriptions-of-new-specimens-from-the-kayenta-formation-of-northern-arizona/39C2921EDC6E951AC9F94A22158CA4E5", use: "Dilophosaurus anatomy and Kayenta Formation occurrence" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; two project-owned identity images used only as anatomy references; external research used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/early-jurassic-frieze-ecosystem-scene-20260803.json#",
        promptRecord: "tools/comfyui/early-jurassic-frieze-ecosystem-scene-20260803.json#prompt",
        prompt: "tools/comfyui/early-jurassic-frieze-ecosystem-scene-20260803.json#prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image with two anatomy-only project references; first output passed ecosystem-scene review",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size ecosystem-scene pass; tiny fourth manual digit, far toes, and osteoderms remain scene-scale limitations." },
        ecology: { status: "supported", note: "Formation/facies context is supported; a shared bed, meeting, and direct behavior are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "allosaurus-camarasaurus-morrison",
      timeBinId: "late-jurassic",
      sceneType: "coexistence",
      title: "강을 사이에 둔 알로사우루스와 카마라사우루스",
      summary: "모리슨층의 같은 채석장 동물상에 포함된 두 종을 서로 다른 강변 단으로 분리한 공존 가설입니다.",
      asset: {
        src: "assets/dinosaurs/allosaurus-fragilis-camarasaurus-boxskull-channel-portrait-ecology-imagegen-v3.png",
        width: 1003,
        height: 1568,
        bytes: 2928164,
        sha256: "425d3b9b3840ce8a0865fa74e79c583ebc66238d28a8af286fc978f12d46c2a6",
        orientation: "portrait",
      },
      formation: {
        name: "Morrison Formation",
        context: "Brushy Basin Member; Carnegie Quarry fauna context, not literal fossil positions",
        ageRangeMa: { older: 150.5, younger: 148.5 },
        resolution: "member/quarry-fauna scale, approximate; exact shared moment is unresolved",
      },
      participants: [
        { taxonId: "allosaurus-fragilis", scientificName: "Allosaurus fragilis", role: "focal", certainty: "exact-taxon quarry cooccurrence: high" },
        { taxonId: "camarasaurus-lentus", scientificName: "Camarasaurus lentus", role: "context", certainty: "exact-taxon quarry cooccurrence: high" },
      ],
      compositionKey: "portrait-stacked-river-terraces",
      compositionLabel: "세로형 강변 단층 스택",
      composition: {
        key: "portrait-stacked-river-terraces",
        label: "세로형 강변 단층 스택",
        family: "stacked-terrain",
        orientation: "portrait",
        camera: "mid-height environmental view",
        spatialLayout: "Allosaurus on the lower near terrace and Camarasaurus on the upper far terrace across a broad channel",
        diversityTags: ["stacked-depth", "negative-space-channel", "foreground-predator", "cloud-heavy-sky"],
      },
      epistemic: {
        known: ["Both named taxa occur in the Carnegie Quarry fauna of the Morrison Formation."],
        reconstructed: ["Animal colors, exact positions, river level, vegetation density, cloud cover, and the moment of mutual awareness."],
        boundary: "Cooccurrence only. The scene does not claim pursuit, defense, direct interaction, or literal fossil spacing.",
      },
      evidence: [
        { url: "https://www.nps.gov/dino/learn/nature/dinosaurs-of-dinosaur.htm", use: "Carnegie Quarry fauna and formation context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; project-owned approved identity assets only; external sources used as factual evidence, not artwork inputs.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/allosaurus-fragilis",
        promptRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/allosaurus-fragilis/prompt",
        prompt: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/allosaurus-fragilis/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image followed by a targeted Camarasaurus anatomy correction",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass; scene-scale hands and feet remain lower-confidence and cannot support representative promotion." },
        ecology: { status: "supported", note: "Exact-taxon quarry cooccurrence is supported; direct behavior is explicitly excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "yutyrannus-yixian-ash-channel",
      timeBinId: "early-cretaceous",
      sceneType: "environment-event",
      title: "화산재 수로를 살피는 유티란누스",
      summary: "차가운 온대성 이셴층 호숫가와 얕은 화산재 수로를 환경 중심의 넓은 화면으로 복원했습니다.",
      asset: {
        src: "assets/dinosaurs/yutyrannus-huali-cool-conifer-ashplain-ecology-imagegen-v1.png",
        width: 1536,
        height: 1024,
        bytes: 3358742,
        sha256: "7b87477e572450a67809080b82ca96c69793eb309e1c73dc865890bd26b63718",
        orientation: "landscape",
      },
      formation: {
        name: "Yixian Formation",
        context: "cool-temperate lake margin and volcanic-ash plain; no exact quarry or simultaneous eruption is depicted",
        ageRangeMa: { older: 125.8, younger: 124.1 },
        resolution: "formation-scale radiometric window, rounded to 0.1 Ma",
      },
      participants: [
        { taxonId: "yutyrannus-huali", scientificName: "Yutyrannus huali", role: "focal", certainty: "taxon and filamentous integument: high; white camouflage: hypothetical" },
      ],
      compositionKey: "landscape-single-subject-shallow-channel",
      compositionLabel: "가로형 환경 중심 얕은 수로",
      composition: {
        key: "landscape-single-subject-shallow-channel",
        label: "가로형 환경 중심 얕은 수로",
        family: "environmental-single",
        orientation: "landscape",
        camera: "wide eye-level habitat view",
        spatialLayout: "one complete animal crosses the middle channel while lake, ash shore, forest, and volcanic relief occupy most of the frame",
        diversityTags: ["single-subject", "wide-environment", "shallow-water", "horizontal-layers"],
      },
      epistemic: {
        known: ["Yutyrannus preserves extensive simple filamentous integument.", "The Yixian setting includes volcanic and lacustrine deposits and evidence for a cool Early Cretaceous climate."],
        reconstructed: ["White-gray disruptive color, exact plumage coverage outside preserved regions, channel position, weather, vegetation arrangement, and walking behavior."],
        boundary: "The ash-channel setting is formation-level context, not proof of this individual, weather, season, camouflage function, or a simultaneous volcanic event.",
      },
      evidence: [
        { url: "https://www.nature.com/articles/nature10906", use: "Yutyrannus anatomy and filamentous integument" },
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3069172/", use: "cool Early Cretaceous climate context" },
        { url: "https://academic.oup.com/nsr/article/8/6/nwab063/6223474", use: "Yixian Formation geochronology" },
        { url: "https://www.nature.com/articles/ncomms4151", use: "volcanic and lacustrine formation context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; one project-owned approved Yutyrannus identity reference; external publications used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/yutyrannus-huali-white-camouflage-batch-20260802.json#records/habitat-ecology",
        promptRecord: "tools/comfyui/yutyrannus-huali-white-camouflage-batch-20260802.json#records/habitat-ecology/prompt",
        correctionPromptRecord: "tools/comfyui/yutyrannus-huali-white-camouflage-batch-20260802.json#records/habitat-ecology/correctionPrompt",
        prompt: "tools/comfyui/yutyrannus-huali-white-camouflage-batch-20260802.json#records/habitat-ecology/prompt",
        seed: "not exposed by generator",
        workflow: "reference-guided generation followed by a localized crest correction",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size habitat-ecology pass after crest correction; this remains non-representative." },
        ecology: { status: "supported", note: "Formation-level climate, lake, and volcanic-ash context is supported while the exact scene remains reconstructed." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "velociraptor-protoceratops-djadokhta",
      timeBinId: "late-cretaceous",
      sceneType: "predation-tension",
      title: "먼지 전선 앞의 벨로키랍토르와 프로토케라톱스",
      summary: "직접 접촉 화석이 알려진 두 종을 공격 장면 대신 넓은 거리를 둔 경계 장면으로 바꿔 보여 줍니다.",
      asset: {
        src: "assets/dinosaurs/velociraptor-mongoliensis-protoceratops-dustfront-portrait-ecology-imagegen-v2.png",
        width: 1003,
        height: 1568,
        bytes: 2975697,
        sha256: "f778224e812d2c576f6c2ca395b20b49e94ad42b03c2ad904079af42a7ff8fe6",
        orientation: "portrait",
      },
      formation: {
        name: "Djadokhta Formation",
        context: "formation-level dune margin; the Fighting Dinosaurs fossil pose and exact locality are not recreated",
        ageRangeMa: { older: 75.0, younger: 71.0 },
        resolution: "formation/stage-scale approximate range; exact illustrated horizon is unresolved",
      },
      participants: [
        { taxonId: "velociraptor-mongoliensis", scientificName: "Velociraptor mongoliensis", role: "focal", certainty: "exact-taxon association: very high" },
        { taxonId: "protoceratops-andrewsi", scientificName: "Protoceratops andrewsi", role: "context", certainty: "exact-taxon association: very high" },
      ],
      compositionKey: "portrait-dustfront-counterdiagonal",
      compositionLabel: "먼지 전선 역대각선",
      composition: {
        key: "portrait-dustfront-counterdiagonal",
        label: "먼지 전선 역대각선",
        family: "counter-diagonal",
        orientation: "portrait",
        camera: "slightly elevated open-basin view",
        spatialLayout: "Velociraptor anchors the lower-left slope while Protoceratops holds the upper-right open plain against a moving dust wall",
        diversityTags: ["counter-diagonal", "dust-front", "open-negative-space", "small-bodied-pair"],
      },
      epistemic: {
        known: ["Velociraptor mongoliensis and Protoceratops andrewsi are preserved together in the Fighting Dinosaurs fossil."],
        reconstructed: ["Separate positions, colors, dust gust, visibility, alert postures, and surrounding dune geometry."],
        boundary: "The direct fossil association is real, but this image does not recreate its pose and makes no new claim about attack sequence or outcome.",
      },
      evidence: [
        { url: "https://www.amnh.org/explore/ology/ology-cards/038-fighting-dinosaurs", use: "exact-taxon direct association and public fossil context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; no external artwork inputs; evidence used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/velociraptor-mongoliensis",
        promptRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/velociraptor-mongoliensis/prompt",
        prompt: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/velociraptor-mongoliensis/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass; small hand and toe counts remain scene-scale limitations." },
        ecology: { status: "supported", note: "Direct exact-taxon association is supported; the image deliberately avoids contact and fossil-pose copying." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "tarbosaurus-saurolophus-nemegt",
      timeBinId: "late-cretaceous",
      sceneType: "predation-tension",
      title: "굽이치는 강 양안의 타르보사우루스와 사우롤로푸스",
      summary: "먹이 흔적은 청소 행동 가능성을 지지하지만, 화면은 사냥 대신 강을 사이에 둔 회피 상황만 보여 줍니다.",
      asset: {
        src: "assets/dinosaurs/tarbosaurus-bataar-saurolophus-rearward-crest-river-portrait-ecology-imagegen-v3.png",
        width: 1122,
        height: 1402,
        bytes: 2635168,
        sha256: "28ee85e3597d78e9f644610e533bfa6e930eec0e547ceaa7f845516911eb9bf4",
        orientation: "portrait",
      },
      formation: {
        name: "Nemegt Formation",
        context: "Bugin Tsav evidence context; the fossil site is not literally depicted",
        ageRangeMa: { older: 70.0, younger: 66.0 },
        resolution: "formation-scale latest Cretaceous range; exact shared moment is unresolved",
      },
      participants: [
        { taxonId: "tarbosaurus-bataar", scientificName: "Tarbosaurus bataar", role: "context", certainty: "exact-taxon formation and feeding-trace association: high" },
        { taxonId: "saurolophus-angustirostris", scientificName: "Saurolophus angustirostris", role: "focal", certainty: "exact-taxon formation and feeding-trace association: high" },
      ],
      compositionKey: "portrait-scurve-river-opposed-banks",
      compositionLabel: "S자 강 양안 원근",
      composition: {
        key: "portrait-scurve-river-opposed-banks",
        label: "S자 강 양안 원근",
        family: "leading-line",
        orientation: "portrait",
        camera: "high environmental view",
        spatialLayout: "Saurolophus dominates the lower-right foreground while Tarbosaurus occupies the upper-left distance across an S-curving river",
        diversityTags: ["s-curve-leading-line", "opposed-banks", "foreground-herbivore", "high-view"],
      },
      epistemic: {
        known: ["Tarbosaurus-associated feeding traces occur on Saurolophus material in the Nemegt Formation."],
        reconstructed: ["Living positions, colors, river course, water level, vegetation, avoidance behavior, and weather."],
        boundary: "Published traces support feeding or scavenging, not a demonstrated live chase or kill; this scene shows no contact.",
      },
      evidence: [
        { url: "https://www.app.pan.pl/archive/published/app55/app20090133.pdf", use: "Nemegt exact-taxon occurrence and feeding-trace interpretation" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; no external artwork inputs; evidence used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tarbosaurus-bataar",
        promptRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tarbosaurus-bataar/prompt",
        prompt: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tarbosaurus-bataar/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image followed by a targeted Saurolophus crest correction",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass after crest correction; exact small digits remain scene-scale limitations." },
        ecology: { status: "supported", note: "Formation association and feeding traces are supported; live pursuit and killing are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "tyrannosaurus-edmontosaurus-hell-creek",
      timeBinId: "late-cretaceous",
      sceneType: "predation-tension",
      title: "안개 습지에서 멈춰 선 티라노사우루스와 에드몬토사우루스",
      summary: "먹이 흔적의 원인은 사냥과 사체 섭식 중 확정할 수 없어, 두 개체가 깊이층을 달리해 멈춘 순간으로 제한했습니다.",
      asset: {
        src: "assets/dinosaurs/tyrannosaurus-rex-edmontosaurus-misty-meadow-pause-portrait-ecology-imagegen-v2.png",
        width: 1003,
        height: 1568,
        bytes: 3032715,
        sha256: "25222ab503f287104a4ae9b45586558f567a8d226db12fca801f7f9c747cdd2b",
        orientation: "portrait",
      },
      formation: {
        name: "Hell Creek Formation",
        context: "formation-level floodplain reconstruction; the cited specimen locality is not depicted",
        ageRangeMa: { older: 67.2, younger: 66.0 },
        resolution: "formation-scale latest Maastrichtian range; exact illustrated horizon is unresolved",
      },
      participants: [
        { taxonId: "tyrannosaurus-rex", scientificName: "Tyrannosaurus rex", role: "context", certainty: "formation cooccurrence and contact evidence: high" },
        { taxonId: "edmontosaurus-annectens", scientificName: "Edmontosaurus annectens", role: "focal", certainty: "formation cooccurrence and contact evidence: high" },
      ],
      compositionKey: "portrait-misty-wetland-depth-layers",
      compositionLabel: "안개 습지 깊이층 정지",
      composition: {
        key: "portrait-misty-wetland-depth-layers",
        label: "안개 습지 깊이층 정지",
        family: "atmospheric-depth",
        orientation: "portrait",
        camera: "low-to-mid wetland view",
        spatialLayout: "large Edmontosaurus fills the lower wetland foreground and Tyrannosaurus stands fully separated on the upper brush line",
        diversityTags: ["layered-depth", "mist", "wetland-reflection", "foreground-herbivore"],
      },
      epistemic: {
        known: ["The exact taxa overlap in the Hell Creek Formation, and tyrannosaurid contact evidence occurs on Edmontosaurus material."],
        reconstructed: ["Living positions, pause behavior, colors, mist, vegetation, wetland depth, and line of sight."],
        boundary: "Contact evidence does not resolve attack versus scavenging; the image depicts neither pursuit nor feeding.",
      },
      evidence: [
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12922588/", use: "exact-taxon Hell Creek contact evidence and its interpretive limits" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; no external artwork inputs; evidence used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tyrannosaurus-rex",
        promptRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tyrannosaurus-rex/prompt",
        prompt: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tyrannosaurus-rex/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass; small Tyrannosaurus fingers and Edmontosaurus soft-tissue details remain lower-confidence." },
        ecology: { status: "supported", note: "Formation overlap and contact evidence are supported; attack versus scavenging remains unresolved and unillustrated." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "triceratops-edmontosaurus-lower-hell-creek",
      timeBinId: "late-cretaceous",
      sceneType: "coexistence",
      title: "하부 헬크리크 수로의 트리케라톱스와 에드몬토사우루스",
      summary: "층서 범위가 겹치는 두 종을 높은 시점과 넓은 수로 음영으로 분리해, 만남이 아닌 공존 가능성만 표현했습니다.",
      asset: {
        src: "assets/dinosaurs/triceratops-horridus-edmontosaurus-lower-hellcreek-portrait-ecology-imagegen-v2.png",
        width: 1003,
        height: 1568,
        bytes: 2900485,
        sha256: "dac6eb1a1c067631ce5ea8858e58a36ed2ab2c54bfde1cf250d6ed0f0085bfe8",
        orientation: "portrait",
      },
      formation: {
        name: "Hell Creek Formation",
        context: "lower stratigraphic interval; formation-level reconstruction with no exact shared locality or moment",
        ageRangeMa: { older: 67.2, younger: 66.5 },
        resolution: "approximate lower-formation overlap window; not an exact shared fossil horizon",
      },
      participants: [
        { taxonId: "triceratops-horridus", scientificName: "Triceratops horridus", role: "focal", certainty: "lower-formation overlap: moderate-high" },
        { taxonId: "edmontosaurus-annectens", scientificName: "Edmontosaurus annectens", role: "context", certainty: "lower-formation overlap: moderate-high" },
      ],
      compositionKey: "portrait-high-oblique-channel-depth-diagonal",
      compositionLabel: "고각 수로 깊이 대각선",
      composition: {
        key: "portrait-high-oblique-channel-depth-diagonal",
        label: "고각 수로 깊이 대각선",
        family: "high-oblique-scale",
        orientation: "portrait",
        camera: "high-oblique foreground close view",
        spatialLayout: "Triceratops fills the lower diagonal foreground while Edmontosaurus remains small on the upper point bar beyond a broad channel",
        diversityTags: ["high-oblique", "channel-depth", "close-foreground", "scale-contrast"],
      },
      epistemic: {
        known: ["Published stratigraphic ranges place the exact taxa in overlapping lower Hell Creek intervals."],
        reconstructed: ["Exact spacing, colors, channel geometry, vegetation, weather, walking direction, and simultaneous presence."],
        boundary: "This is an overlap-window visualization, not evidence of an exact shared locality, direct meeting, herd, or partnership.",
      },
      evidence: [
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4104892/", use: "Triceratops stratigraphic distribution in the Hell Creek Formation" },
        { url: "https://doi.org/10.2110/palo.2017.060", use: "Edmontosaurus-bearing lower Hell Creek stratigraphic context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; project-owned taxon identity assets only; external evidence was not used as artwork input.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/triceratops-horridus",
        promptRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/triceratops-horridus/prompt",
        correctionPromptRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/triceratops-horridus/correctionPrompt",
        prompt: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/triceratops-horridus/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image followed by Edmontosaurus limb-readability correction",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass after Edmontosaurus limb correction; neither animal is representative-eligible from this scene." },
        ecology: { status: "supported", note: "Approximate lower-formation overlap is supported; exact meeting and social behavior are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "parasaurolophus-centrosaurus-lower-dinosaur-park",
      timeBinId: "late-cretaceous",
      sceneType: "coexistence",
      title: "숲길 깊이층의 파라사우롤로푸스와 센트로사우루스",
      summary: "낮은 숲 카메라와 S자 길, 가로지른 통나무를 이용해 두 종을 서로 다른 깊이층에 놓은 지층 공존 가설입니다.",
      asset: {
        src: "assets/dinosaurs/parasaurolophus-walkeri-centrosaurus-forest-scurve-portrait-ecology-imagegen-v3.png",
        width: 1003,
        height: 1568,
        bytes: 3256137,
        sha256: "cdd22717e91c448494cb80237e486ad3e1e2167b81e45782cb32d6725862e13d",
        orientation: "portrait",
      },
      formation: {
        name: "Dinosaur Park Formation",
        context: "lower stratigraphic interval; formation-level reconstruction with no exact shared locality or direct meeting",
        ageRangeMa: { older: 76.9, younger: 76.5 },
        resolution: "approximate lower-formation overlap window; not an exact shared fossil horizon",
      },
      participants: [
        { taxonId: "parasaurolophus-walkeri", scientificName: "Parasaurolophus walkeri", role: "focal", certainty: "lower-formation overlap: moderate" },
        { taxonId: "centrosaurus-apertus", scientificName: "Centrosaurus apertus", role: "context", certainty: "lower-formation overlap: moderate" },
      ],
      compositionKey: "portrait-low-forest-scurve-zdepth",
      compositionLabel: "낮은 숲길 S자 Z심도",
      composition: {
        key: "portrait-low-forest-scurve-zdepth",
        label: "낮은 숲길 S자 Z심도",
        family: "foreground-framing",
        orientation: "portrait",
        camera: "low forest-floor view",
        spatialLayout: "Parasaurolophus crosses the lower-left path, a horizontal log divides the frame, and Centrosaurus occupies the upper-right terrace",
        diversityTags: ["low-camera", "s-curve-trail", "horizontal-log", "forest-frame", "z-depth"],
      },
      epistemic: {
        known: ["Published stratigraphic ranges overlap for the exact taxa in the lower Dinosaur Park Formation."],
        reconstructed: ["Exact spacing, colors, forest density, path, fallen log, sun shafts, walking direction, and simultaneous presence."],
        boundary: "The image visualizes a formation-range overlap only; it does not claim a shared locality, direct encounter, herd, or partnership.",
      },
      evidence: [
        { url: "https://rune.une.edu.au/web/handle/1959.11/27585", use: "Parasaurolophus walkeri stratigraphic position" },
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3933270/", use: "Centrosaurus apertus Dinosaur Park stratigraphic distribution" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; project-owned taxon identity assets only; external evidence was not used as artwork input.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/parasaurolophus-walkeri",
        promptRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/parasaurolophus-walkeri/prompt",
        prompt: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/parasaurolophus-walkeri/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image after rejecting repeated river compositions and failed crowded forest attempts",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass; exact small digits remain scene-scale limitations and the scene cannot become representative." },
        ecology: { status: "supported", note: "Approximate lower-formation overlap is supported; exact meeting and social behavior are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
  ],
};
