// Curated ecosystem-scene catalog. This data is intentionally independent from
// representative dinosaur cards: every scene remains in a separate review lane.
window.ecosystemSceneCatalog = {
  schemaVersion: 1,
  generatedAt: "2026-08-03T09:49:24.000Z",
  policy: {
    targetAudience: "ages 5-14",
    representativePromotion: "prohibited; ecosystem scenes are never representative-card candidates",
    evidenceBoundary: "Formation overlap or fossil association does not by itself prove the exact meeting, pose, weather, pursuit, herd, or event shown.",
    publicationRule: "A scene may be published only when anatomy, ecology, and responsive gates are supported.",
    compositionDiversityRule: "Every scene requires a unique composition key and a distinct camera-plus-spatial-layout signature.",
  },
  sceneTypes: [
    { id: "coexistence", label: "공존" },
    { id: "predation-tension", label: "포식 긴장" },
    { id: "herd-growth", label: "무리·성장" },
    { id: "environment-event", label: "환경·사건" },
    { id: "trace-evidence", label: "발자국·흔적" },
  ],
  timeBins: [
    {
      id: "late-triassic",
      label: "후기 트라이아스기",
      era: "triassic",
      ageRangeMa: { older: 237.0, younger: 201.4 },
      sceneIds: [
        "eoraptor-herrerasaurus-cancha-de-bochas",
        "buriolestes-candelaria-macrocharcoal-wildfire-composite",
        "eoraptor-chromogisaurus-cancha-de-bochas-weathered-ash-bank",
      ],
    },
    {
      id: "early-jurassic",
      label: "전기 쥐라기",
      era: "jurassic",
      ageRangeMa: { older: 201.4, younger: 174.7 },
      sceneIds: ["scutellosaurus-dilophosaurus-kayenta"],
    },
    {
      id: "middle-jurassic",
      label: "중기 쥐라기",
      era: "jurassic",
      ageRangeMa: { older: 174.7, younger: 161.5 },
      sceneIds: ["dewars-farm-sauropod-theropod-crossing-trackways"],
    },
    {
      id: "late-jurassic",
      label: "후기 쥐라기",
      era: "jurassic",
      ageRangeMa: { older: 161.5, younger: 143.1 },
      sceneIds: ["allosaurus-camarasaurus-morrison"],
    },
    {
      id: "early-cretaceous",
      label: "전기 백악기",
      era: "cretaceous",
      ageRangeMa: { older: 143.1, younger: 100.5 },
      sceneIds: ["yutyrannus-yixian-ash-channel"],
    },
    {
      id: "late-cretaceous",
      label: "후기 백악기",
      era: "cretaceous",
      ageRangeMa: { older: 100.5, younger: 66.0 },
      sceneIds: [
        "parasaurolophus-centrosaurus-lower-dinosaur-park",
        "protoceratops-juvenile-aggregation-djadokhta",
        "velociraptor-protoceratops-djadokhta",
        "tarbosaurus-saurolophus-nemegt",
        "triceratops-edmontosaurus-lower-hell-creek",
        "tyrannosaurus-edmontosaurus-hell-creek",
        "tyrannosaurus-edmontosaurus-kpg-dim-sky",
      ],
    },
  ],
  scenes: [
    {
      id: "eoraptor-herrerasaurus-cancha-de-bochas",
      timeBinId: "late-triassic",
      sceneType: "coexistence",
      title: "동심원 지형을 사이에 둔 에오랍토르와 헤레라사우루스",
      summary: "같은 낮은 층준에서 보고된 두 종을 넓은 빈 땅과 반대 이동축으로 분리한 후기 트라이아스기 공존 복원입니다.",
      asset: {
        src: "assets/dinosaurs/eoraptor-lunensis-herrerasaurus-cancha-de-bochas-high-oblique-concentric-coexistence-imagegen-v1.png",
        width: 1122,
        height: 1402,
        bytes: 3476030,
        sha256: "3461013156e1b114398851e77c989a0a5d057b30b0e84784c7156db4dd219cb7",
        orientation: "portrait",
      },
      formation: {
        name: "Ischigualasto Formation, Cancha de Bochas Member",
        context: "lowermost Cancha de Bochas level and well-drained floodplain context; not literal fossil positions",
        ageRangeMa: { older: 233.0, younger: 225.0 },
        resolution: "same cited low member level; exact shared moment and spacing unresolved",
      },
      participants: [
        { taxonId: "eoraptor-lunensis", scientificName: "Eoraptor lunensis", role: "context", certainty: "same cited low member level: high" },
        { taxonId: "herrerasaurus-ischigualastensis", scientificName: "Herrerasaurus ischigualastensis", role: "focal", certainty: "same cited low member level: high" },
      ],
      compositionKey: "portrait-high-oblique-concentric-paleosol",
      compositionLabel: "고각도 동심원 지형 분리",
      composition: {
        key: "portrait-high-oblique-concentric-paleosol",
        label: "고각도 동심원 지형 분리",
        family: "radial-landform",
        orientation: "portrait",
        camera: "high diagonal near-top-down portrait field-observation view",
        spatialLayout: "small Eoraptor in the upper third and larger Herrerasaurus in the lower third, separated by concentric paleosol rings and opposing travel axes",
        diversityTags: ["high-oblique", "concentric-ground", "upper-lower-split", "opposed-directions"],
      },
      epistemic: {
        known: ["The cited study reports Eoraptor and Herrerasaurus from the same low level of the Cancha de Bochas Member."],
        reconstructed: ["Concentric paleosol rings, exact spacing, colors, weather, walking directions, and simultaneous presence are reconstructed."],
        boundary: "The scene communicates stratigraphic coexistence only and does not claim a meeting, pursuit, mutual awareness, or direct interaction.",
      },
      evidence: [
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3088398/", use: "same low member level and floodplain context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; two project-owned identity images used only as anatomy references; external research used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/triassic-concentric-ecosystem-scene-20260803.json#",
        promptRecord: "tools/comfyui/triassic-concentric-ecosystem-scene-20260803.json#prompt",
        prompt: "tools/comfyui/triassic-concentric-ecosystem-scene-20260803.json#prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image with two anatomy-only project references; first output passed ecosystem-scene review",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size ecosystem-scene pass; scene-scale digits remain lower-confidence and cannot support representative promotion." },
        ecology: { status: "supported", note: "Same cited low-member level is supported; exact meeting and behavior are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "buriolestes-candelaria-macrocharcoal-wildfire-composite",
      timeBinId: "late-triassic",
      sceneType: "environment-event",
      title: "숯 기록에서 출발한 칸델라리아 산불 풍경",
      summary: "피녜이루 마샤두의 여러 퇴적층에서 나온 숯 화석과, 별도 부리올 산지의 부리올레스테스를 시대·지역 수준으로 합친 교육 복원입니다. 같은 노두·같은 화재·직접 목격이나 화재 직후 생존을 뜻하지 않습니다.",
      asset: {
        src: "assets/dinosaurs/buriolestes-schultzi-candelaria-macrocharcoal-wildfire-composite-ecology-imagegen-v1.png",
        width: 1536,
        height: 1024,
        bytes: 3581621,
        sha256: "6c9c782bca45cbe75d39809ad3b4a93b5442302fbc80800e072156ccfa07c325",
        orientation: "landscape",
      },
      formation: {
        name: "Candelária Sequence, Santa Maria Supersequence — regional composite",
        context: "macro-charcoal-bearing Pinheiro Machado/Arroio Moirão Graben section and the Buriolestes-bearing Buriol outcrop at São João do Polêsine combined only at sequence and regional scale",
        ageRangeMa: { older: 237.0, younger: 227.3 },
        resolution: "Carnian sequence/region-scale composite; exact bed correlation unresolved; Buriolestes is not recorded at the cited charcoal locality",
      },
      participants: [
        {
          taxonId: "buriolestes-schultzi",
          scientificName: "Buriolestes schultzi",
          role: "separate-site sequence-fauna context",
          certainty: "Buriol site occurrence: high; association with the cited charcoal section or one fire event: unsupported",
        },
      ],
      compositionKey: "landscape-charcoal-foreground-diagonal-runoff",
      compositionLabel: "숯 전경과 대각선 물길 모자이크",
      composition: {
        key: "landscape-charcoal-foreground-diagonal-runoff",
        label: "숯 전경과 대각선 물길 모자이크",
        family: "charcoal-evidence-mosaic",
        orientation: "landscape",
        camera: "low-to-mid oblique landscape habitat-observation view",
        spatialLayout: "a dark triangular charcoal field occupies the lower-left foreground, a wet red-mud runoff strip crosses diagonally through the center, and one small Buriolestes remains isolated in the right midground",
        diversityTags: ["charcoal-foreground", "diagonal-runoff", "material-mosaic", "small-context-animal"],
      },
      epistemic: {
        known: [
          "Macro-charcoal in sandstone-siltstone facies of one Candelária Sequence section supports recurrent wildfire under seasonal wet and dry conditions.",
          "Buriolestes schultzi is documented from the separate Buriol outcrop at São João do Polêsine in the Carnian Candelária Sequence context.",
        ],
        reconstructed: [
          "The shared frame, exact postfire interval, wet ground, charcoal distribution, vegetation, color, animal pose and behavior are reconstructed.",
          "The animal and charcoal evidence come from different localities and are combined only to teach a broader sequence-level environmental possibility.",
        ],
        boundary: "Buriolestes is not recorded at the cited charcoal locality. This scene does not claim the same outcrop, bed, wildfire, day or place, or that this individual witnessed, fled or survived immediately after a documented fire.",
      },
      displayEpistemic: {
        known: [
          "피녜이루 마샤두의 칸델라리아 수열 여러 퇴적층에서는 눈에 보이는 크기의 숯 화석이 발견되어, 산불이 되풀이되었음을 알려 줘요.",
          "부리올레스테스는 같은 지층 수열이지만 다른 지역인 상주앙두폴레지니의 부리올 산지에서 알려져 있어요.",
        ],
        reconstructed: [
          "숯 조각의 위치, 비가 온 시점, 식생과 한 개체의 자세는 당시 환경을 설명하려고 상상해 배치했어요.",
        ],
        boundary: "숯이 나온 곳과 부리올레스테스 산지는 서로 다릅니다. 같은 화재나 시점도 알 수 없고, 이 개체가 불을 보거나 피했거나 화재 직후 살아남았다는 뜻도 아니에요.",
        context: "서로 다른 산지의 증거를 시대·지역 수준으로 묶은 환경 복원",
        participantHeading: "별도 유적에서 알려진 동물",
      },
      evidence: [
        { url: "https://doi.org/10.1016/j.jsames.2017.12.018", use: "macro-charcoal and recurrent wildfire in the Pinheiro Machado Candelária Sequence section" },
        { url: "https://doi.org/10.1016/j.cub.2016.09.040", use: "Buriolestes original description and Buriol locality" },
        { url: "https://www.app.pan.pl/archive/published/app62/app003692017.html", use: "Buriol outcrop stratigraphic context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation using two project-owned Buriolestes images only as anatomy references; no external artwork or paper-figure pixels used.",
        license: "Generated project asset; distribution follows project and image-generation account terms. Research sources support factual claims only and are not image references.",
        metadataRecord: "tools/comfyui/triassic-macrocharcoal-buriolestes-ecosystem-scene-20260803.json#",
        promptRecord: "tools/comfyui/triassic-macrocharcoal-buriolestes-ecosystem-scene-20260803.json#prompt",
        prompt: "tools/comfyui/triassic-macrocharcoal-buriolestes-ecosystem-scene-20260803.json#prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image with two anatomy-only project references; first output passed independent anatomy, composition and age-safety review",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Independent original-size review passed exactly one Buriolestes with two separated forelimbs, two hind limbs and one continuous tail; tiny digits remain non-diagnostic." },
        ecology: { status: "supported", note: "Wildfire evidence and Buriolestes occurrence are supported separately; the different localities, shared frame and behavior are explicitly reconstructed." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x1000, 390x844, 320x700 and 844x390: 1536x1024 decode, contain, no overflow, isolated filtering, tap-hide and image-only pinch." },
        publication: { status: "published", note: "Anatomy, ecology, composition, locality boundary, age-safety and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "scutellosaurus-dilophosaurus-kayenta",
      timeBinId: "early-jurassic",
      sceneType: "coexistence",
      title: "붉은 평원을 가로지르는 스쿠텔로사우루스와 딜로포사우루스",
      summary: "카옌타층 동물상 두 종을 화면 양끝과 서로 다른 깊이에 놓은 전기 쥐라기 지층 단위 공존 복원입니다.",
      asset: {
        src: "assets/dinosaurs/scutellosaurus-lawleri-dilophosaurus-kayenta-groundlevel-longlens-frieze-coexistence-imagegen-v1.png",
        width: 1672,
        height: 941,
        bytes: 2837221,
        sha256: "fe643e98e890b23d62ad97ec811935838372378df16ffdccc22bce58d00ceb29",
        orientation: "landscape",
      },
      formation: {
        name: "Kayenta Formation",
        context: "silty-facies fauna and red floodplain/dune-margin context; not one exact shared bed",
        ageRangeMa: { older: 199.3, younger: 182.7 },
        resolution: "formation/facies scale; exact horizon, encounter, and simultaneous presence unresolved",
      },
      participants: [
        { taxonId: "scutellosaurus-lawleri", scientificName: "Scutellosaurus lawleri", role: "context", certainty: "Kayenta silty-facies occurrence: high; exact shared bed: unresolved" },
        { taxonId: "dilophosaurus-wetherilli", scientificName: "Dilophosaurus wetherilli", role: "focal", certainty: "Kayenta occurrence: high; exact shared bed: unresolved" },
      ],
      compositionKey: "landscape-groundlevel-longlens-vertical-frieze",
      compositionLabel: "지면 높이 세 구역 프리즈",
      composition: {
        key: "landscape-groundlevel-longlens-vertical-frieze",
        label: "지면 높이 세 구역 프리즈",
        family: "transverse-frieze",
        orientation: "landscape",
        camera: "ground-height long-telephoto landscape view",
        spatialLayout: "Dilophosaurus occupies the far-left middle distance and Scutellosaurus the far-right near plane, facing outward across a broad empty center divided by vertical trunks",
        diversityTags: ["vertical-frieze", "long-lens", "edge-separated", "opposed-directions"],
      },
      epistemic: {
        known: ["Both named taxa are documented from the Kayenta Formation, with Scutellosaurus associated with its silty facies."],
        reconstructed: ["Exact co-presence, spacing, travel directions, colors, plants, dune margin, and weather are reconstructed."],
        boundary: "This is a formation-level fauna comparison and does not claim one shared bed, a real encounter, pursuit, or predator-prey behavior.",
      },
      evidence: [
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8292774/", use: "Scutellosaurus anatomy and Kayenta silty-facies context" },
        { url: "https://www.cambridge.org/core/journals/journal-of-paleontology/article/comprehensive-anatomical-and-phylogenetic-evaluation-of-dilophosaurus-wetherilli-dinosauria-theropoda-with-descriptions-of-new-specimens-from-the-kayenta-formation-of-northern-arizona/39C2921EDC6E951AC9F94A22158CA4E5", use: "Dilophosaurus anatomy and Kayenta Formation occurrence" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; two project-owned identity images used only as anatomy references; external research used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/early-jurassic-frieze-ecosystem-scene-20260803.json#",
        promptRecord: "tools/comfyui/early-jurassic-frieze-ecosystem-scene-20260803.json#prompt",
        prompt: "tools/comfyui/early-jurassic-frieze-ecosystem-scene-20260803.json#prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image with two anatomy-only project references; first output passed ecosystem-scene review",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size ecosystem-scene pass; tiny fourth manual digit, far toes, and osteoderms remain scene-scale limitations." },
        ecology: { status: "supported", note: "Formation/facies context is supported; a shared bed, meeting, and direct behavior are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "allosaurus-camarasaurus-morrison",
      timeBinId: "late-jurassic",
      sceneType: "coexistence",
      title: "강을 사이에 둔 알로사우루스와 카마라사우루스",
      summary: "모리슨층의 같은 채석장 동물상에 포함된 두 종을 서로 다른 강변 단으로 분리한 공존 가설입니다.",
      asset: {
        src: "assets/dinosaurs/allosaurus-fragilis-camarasaurus-boxskull-channel-portrait-ecology-imagegen-v3.png",
        width: 1003,
        height: 1568,
        bytes: 2928164,
        sha256: "425d3b9b3840ce8a0865fa74e79c583ebc66238d28a8af286fc978f12d46c2a6",
        orientation: "portrait",
      },
      formation: {
        name: "Morrison Formation",
        context: "Brushy Basin Member; Carnegie Quarry fauna context, not literal fossil positions",
        ageRangeMa: { older: 150.5, younger: 148.5 },
        resolution: "member/quarry-fauna scale, approximate; exact shared moment is unresolved",
      },
      participants: [
        { taxonId: "allosaurus-fragilis", scientificName: "Allosaurus fragilis", role: "focal", certainty: "exact-taxon quarry cooccurrence: high" },
        { taxonId: "camarasaurus-lentus", scientificName: "Camarasaurus lentus", role: "context", certainty: "exact-taxon quarry cooccurrence: high" },
      ],
      compositionKey: "portrait-stacked-river-terraces",
      compositionLabel: "세로형 강변 단층 스택",
      composition: {
        key: "portrait-stacked-river-terraces",
        label: "세로형 강변 단층 스택",
        family: "stacked-terrain",
        orientation: "portrait",
        camera: "mid-height environmental view",
        spatialLayout: "Allosaurus on the lower near terrace and Camarasaurus on the upper far terrace across a broad channel",
        diversityTags: ["stacked-depth", "negative-space-channel", "foreground-predator", "cloud-heavy-sky"],
      },
      epistemic: {
        known: ["Both named taxa occur in the Carnegie Quarry fauna of the Morrison Formation."],
        reconstructed: ["Animal colors, exact positions, river level, vegetation density, cloud cover, and the moment of mutual awareness."],
        boundary: "Cooccurrence only. The scene does not claim pursuit, defense, direct interaction, or literal fossil spacing.",
      },
      evidence: [
        { url: "https://www.nps.gov/dino/learn/nature/dinosaurs-of-dinosaur.htm", use: "Carnegie Quarry fauna and formation context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; project-owned approved identity assets only; external sources used as factual evidence, not artwork inputs.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/allosaurus-fragilis",
        promptRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/allosaurus-fragilis/prompt",
        prompt: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/allosaurus-fragilis/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image followed by a targeted Camarasaurus anatomy correction",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass; scene-scale hands and feet remain lower-confidence and cannot support representative promotion." },
        ecology: { status: "supported", note: "Exact-taxon quarry cooccurrence is supported; direct behavior is explicitly excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "yutyrannus-yixian-ash-channel",
      timeBinId: "early-cretaceous",
      sceneType: "environment-event",
      title: "화산재 수로를 살피는 유티란누스",
      summary: "차가운 온대성 이셴층 호숫가와 얕은 화산재 수로를 환경 중심의 넓은 화면으로 복원했습니다.",
      asset: {
        src: "assets/dinosaurs/yutyrannus-huali-cool-conifer-ashplain-ecology-imagegen-v1.png",
        width: 1536,
        height: 1024,
        bytes: 3358742,
        sha256: "7b87477e572450a67809080b82ca96c69793eb309e1c73dc865890bd26b63718",
        orientation: "landscape",
      },
      formation: {
        name: "Yixian Formation",
        context: "cool-temperate lake margin and volcanic-ash plain; no exact quarry or simultaneous eruption is depicted",
        ageRangeMa: { older: 125.8, younger: 124.1 },
        resolution: "formation-scale radiometric window, rounded to 0.1 Ma",
      },
      participants: [
        { taxonId: "yutyrannus-huali", scientificName: "Yutyrannus huali", role: "focal", certainty: "taxon and filamentous integument: high; white camouflage: hypothetical" },
      ],
      compositionKey: "landscape-single-subject-shallow-channel",
      compositionLabel: "가로형 환경 중심 얕은 수로",
      composition: {
        key: "landscape-single-subject-shallow-channel",
        label: "가로형 환경 중심 얕은 수로",
        family: "environmental-single",
        orientation: "landscape",
        camera: "wide eye-level habitat view",
        spatialLayout: "one complete animal crosses the middle channel while lake, ash shore, forest, and volcanic relief occupy most of the frame",
        diversityTags: ["single-subject", "wide-environment", "shallow-water", "horizontal-layers"],
      },
      epistemic: {
        known: ["Yutyrannus preserves extensive simple filamentous integument.", "The Yixian setting includes volcanic and lacustrine deposits and evidence for a cool Early Cretaceous climate."],
        reconstructed: ["White-gray disruptive color, exact plumage coverage outside preserved regions, channel position, weather, vegetation arrangement, and walking behavior."],
        boundary: "The ash-channel setting is formation-level context, not proof of this individual, weather, season, camouflage function, or a simultaneous volcanic event.",
      },
      evidence: [
        { url: "https://www.nature.com/articles/nature10906", use: "Yutyrannus anatomy and filamentous integument" },
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3069172/", use: "cool Early Cretaceous climate context" },
        { url: "https://academic.oup.com/nsr/article/8/6/nwab063/6223474", use: "Yixian Formation geochronology" },
        { url: "https://www.nature.com/articles/ncomms4151", use: "volcanic and lacustrine formation context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; one project-owned approved Yutyrannus identity reference; external publications used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/yutyrannus-huali-white-camouflage-batch-20260802.json#records/habitat-ecology",
        promptRecord: "tools/comfyui/yutyrannus-huali-white-camouflage-batch-20260802.json#records/habitat-ecology/prompt",
        correctionPromptRecord: "tools/comfyui/yutyrannus-huali-white-camouflage-batch-20260802.json#records/habitat-ecology/correctionPrompt",
        prompt: "tools/comfyui/yutyrannus-huali-white-camouflage-batch-20260802.json#records/habitat-ecology/prompt",
        seed: "not exposed by generator",
        workflow: "reference-guided generation followed by a localized crest correction",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size habitat-ecology pass after crest correction; this remains non-representative." },
        ecology: { status: "supported", note: "Formation-level climate, lake, and volcanic-ash context is supported while the exact scene remains reconstructed." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "velociraptor-protoceratops-djadokhta",
      timeBinId: "late-cretaceous",
      sceneType: "predation-tension",
      title: "먼지 전선 앞의 벨로키랍토르와 프로토케라톱스",
      summary: "직접 접촉 화석이 알려진 두 종을 공격 장면 대신 넓은 거리를 둔 경계 장면으로 바꿔 보여 줍니다.",
      asset: {
        src: "assets/dinosaurs/velociraptor-mongoliensis-protoceratops-dustfront-portrait-ecology-imagegen-v2.png",
        width: 1003,
        height: 1568,
        bytes: 2975697,
        sha256: "f778224e812d2c576f6c2ca395b20b49e94ad42b03c2ad904079af42a7ff8fe6",
        orientation: "portrait",
      },
      formation: {
        name: "Djadokhta Formation",
        context: "formation-level dune margin; the Fighting Dinosaurs fossil pose and exact locality are not recreated",
        ageRangeMa: { older: 75.0, younger: 71.0 },
        resolution: "formation/stage-scale approximate range; exact illustrated horizon is unresolved",
      },
      participants: [
        { taxonId: "velociraptor-mongoliensis", scientificName: "Velociraptor mongoliensis", role: "focal", certainty: "exact-taxon association: very high" },
        { taxonId: "protoceratops-andrewsi", scientificName: "Protoceratops andrewsi", role: "context", certainty: "exact-taxon association: very high" },
      ],
      compositionKey: "portrait-dustfront-counterdiagonal",
      compositionLabel: "먼지 전선 역대각선",
      composition: {
        key: "portrait-dustfront-counterdiagonal",
        label: "먼지 전선 역대각선",
        family: "counter-diagonal",
        orientation: "portrait",
        camera: "slightly elevated open-basin view",
        spatialLayout: "Velociraptor anchors the lower-left slope while Protoceratops holds the upper-right open plain against a moving dust wall",
        diversityTags: ["counter-diagonal", "dust-front", "open-negative-space", "small-bodied-pair"],
      },
      epistemic: {
        known: ["Velociraptor mongoliensis and Protoceratops andrewsi are preserved together in the Fighting Dinosaurs fossil."],
        reconstructed: ["Separate positions, colors, dust gust, visibility, alert postures, and surrounding dune geometry."],
        boundary: "The direct fossil association is real, but this image does not recreate its pose and makes no new claim about attack sequence or outcome.",
      },
      evidence: [
        { url: "https://www.amnh.org/explore/ology/ology-cards/038-fighting-dinosaurs", use: "exact-taxon direct association and public fossil context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; no external artwork inputs; evidence used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/velociraptor-mongoliensis",
        promptRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/velociraptor-mongoliensis/prompt",
        prompt: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/velociraptor-mongoliensis/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass; small hand and toe counts remain scene-scale limitations." },
        ecology: { status: "supported", note: "Direct exact-taxon association is supported; the image deliberately avoids contact and fossil-pose copying." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "tarbosaurus-saurolophus-nemegt",
      timeBinId: "late-cretaceous",
      sceneType: "predation-tension",
      title: "굽이치는 강 양안의 타르보사우루스와 사우롤로푸스",
      summary: "먹이 흔적은 청소 행동 가능성을 지지하지만, 화면은 사냥 대신 강을 사이에 둔 회피 상황만 보여 줍니다.",
      asset: {
        src: "assets/dinosaurs/tarbosaurus-bataar-saurolophus-rearward-crest-river-portrait-ecology-imagegen-v3.png",
        width: 1122,
        height: 1402,
        bytes: 2635168,
        sha256: "28ee85e3597d78e9f644610e533bfa6e930eec0e547ceaa7f845516911eb9bf4",
        orientation: "portrait",
      },
      formation: {
        name: "Nemegt Formation",
        context: "Bugin Tsav evidence context; the fossil site is not literally depicted",
        ageRangeMa: { older: 70.0, younger: 66.0 },
        resolution: "formation-scale latest Cretaceous range; exact shared moment is unresolved",
      },
      participants: [
        { taxonId: "tarbosaurus-bataar", scientificName: "Tarbosaurus bataar", role: "context", certainty: "exact-taxon formation and feeding-trace association: high" },
        { taxonId: "saurolophus-angustirostris", scientificName: "Saurolophus angustirostris", role: "focal", certainty: "exact-taxon formation and feeding-trace association: high" },
      ],
      compositionKey: "portrait-scurve-river-opposed-banks",
      compositionLabel: "S자 강 양안 원근",
      composition: {
        key: "portrait-scurve-river-opposed-banks",
        label: "S자 강 양안 원근",
        family: "leading-line",
        orientation: "portrait",
        camera: "high environmental view",
        spatialLayout: "Saurolophus dominates the lower-right foreground while Tarbosaurus occupies the upper-left distance across an S-curving river",
        diversityTags: ["s-curve-leading-line", "opposed-banks", "foreground-herbivore", "high-view"],
      },
      epistemic: {
        known: ["Tarbosaurus-associated feeding traces occur on Saurolophus material in the Nemegt Formation."],
        reconstructed: ["Living positions, colors, river course, water level, vegetation, avoidance behavior, and weather."],
        boundary: "Published traces support feeding or scavenging, not a demonstrated live chase or kill; this scene shows no contact.",
      },
      evidence: [
        { url: "https://www.app.pan.pl/archive/published/app55/app20090133.pdf", use: "Nemegt exact-taxon occurrence and feeding-trace interpretation" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; no external artwork inputs; evidence used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tarbosaurus-bataar",
        promptRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tarbosaurus-bataar/prompt",
        prompt: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tarbosaurus-bataar/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image followed by a targeted Saurolophus crest correction",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass after crest correction; exact small digits remain scene-scale limitations." },
        ecology: { status: "supported", note: "Formation association and feeding traces are supported; live pursuit and killing are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "tyrannosaurus-edmontosaurus-hell-creek",
      timeBinId: "late-cretaceous",
      sceneType: "predation-tension",
      title: "안개 습지에서 멈춰 선 티라노사우루스와 에드몬토사우루스",
      summary: "먹이 흔적의 원인은 사냥과 사체 섭식 중 확정할 수 없어, 두 개체가 깊이층을 달리해 멈춘 순간으로 제한했습니다.",
      asset: {
        src: "assets/dinosaurs/tyrannosaurus-rex-edmontosaurus-misty-meadow-pause-portrait-ecology-imagegen-v2.png",
        width: 1003,
        height: 1568,
        bytes: 3032715,
        sha256: "25222ab503f287104a4ae9b45586558f567a8d226db12fca801f7f9c747cdd2b",
        orientation: "portrait",
      },
      formation: {
        name: "Hell Creek Formation",
        context: "formation-level floodplain reconstruction; the cited specimen locality is not depicted",
        ageRangeMa: { older: 67.2, younger: 66.0 },
        resolution: "formation-scale latest Maastrichtian range; exact illustrated horizon is unresolved",
      },
      participants: [
        { taxonId: "tyrannosaurus-rex", scientificName: "Tyrannosaurus rex", role: "context", certainty: "formation cooccurrence and contact evidence: high" },
        { taxonId: "edmontosaurus-annectens", scientificName: "Edmontosaurus annectens", role: "focal", certainty: "formation cooccurrence and contact evidence: high" },
      ],
      compositionKey: "portrait-misty-wetland-depth-layers",
      compositionLabel: "안개 습지 깊이층 정지",
      composition: {
        key: "portrait-misty-wetland-depth-layers",
        label: "안개 습지 깊이층 정지",
        family: "atmospheric-depth",
        orientation: "portrait",
        camera: "low-to-mid wetland view",
        spatialLayout: "large Edmontosaurus fills the lower wetland foreground and Tyrannosaurus stands fully separated on the upper brush line",
        diversityTags: ["layered-depth", "mist", "wetland-reflection", "foreground-herbivore"],
      },
      epistemic: {
        known: ["The exact taxa overlap in the Hell Creek Formation, and tyrannosaurid contact evidence occurs on Edmontosaurus material."],
        reconstructed: ["Living positions, pause behavior, colors, mist, vegetation, wetland depth, and line of sight."],
        boundary: "Contact evidence does not resolve attack versus scavenging; the image depicts neither pursuit nor feeding.",
      },
      evidence: [
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12922588/", use: "exact-taxon Hell Creek contact evidence and its interpretive limits" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; no external artwork inputs; evidence used only for factual constraints.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tyrannosaurus-rex",
        promptRecord: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tyrannosaurus-rex/prompt",
        prompt: "tools/comfyui/lv1-portrait-ecology-batch-20260802.json#records/tyrannosaurus-rex/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass; small Tyrannosaurus fingers and Edmontosaurus soft-tissue details remain lower-confidence." },
        ecology: { status: "supported", note: "Formation overlap and contact evidence are supported; attack versus scavenging remains unresolved and unillustrated." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "triceratops-edmontosaurus-lower-hell-creek",
      timeBinId: "late-cretaceous",
      sceneType: "coexistence",
      title: "하부 헬크리크 수로의 트리케라톱스와 에드몬토사우루스",
      summary: "층서 범위가 겹치는 두 종을 높은 시점과 넓은 수로 음영으로 분리해, 만남이 아닌 공존 가능성만 표현했습니다.",
      asset: {
        src: "assets/dinosaurs/triceratops-horridus-edmontosaurus-lower-hellcreek-portrait-ecology-imagegen-v2.png",
        width: 1003,
        height: 1568,
        bytes: 2900485,
        sha256: "dac6eb1a1c067631ce5ea8858e58a36ed2ab2c54bfde1cf250d6ed0f0085bfe8",
        orientation: "portrait",
      },
      formation: {
        name: "Hell Creek Formation",
        context: "lower stratigraphic interval; formation-level reconstruction with no exact shared locality or moment",
        ageRangeMa: { older: 67.2, younger: 66.5 },
        resolution: "approximate lower-formation overlap window; not an exact shared fossil horizon",
      },
      participants: [
        { taxonId: "triceratops-horridus", scientificName: "Triceratops horridus", role: "focal", certainty: "lower-formation overlap: moderate-high" },
        { taxonId: "edmontosaurus-annectens", scientificName: "Edmontosaurus annectens", role: "context", certainty: "lower-formation overlap: moderate-high" },
      ],
      compositionKey: "portrait-high-oblique-channel-depth-diagonal",
      compositionLabel: "고각 수로 깊이 대각선",
      composition: {
        key: "portrait-high-oblique-channel-depth-diagonal",
        label: "고각 수로 깊이 대각선",
        family: "high-oblique-scale",
        orientation: "portrait",
        camera: "high-oblique foreground close view",
        spatialLayout: "Triceratops fills the lower diagonal foreground while Edmontosaurus remains small on the upper point bar beyond a broad channel",
        diversityTags: ["high-oblique", "channel-depth", "close-foreground", "scale-contrast"],
      },
      epistemic: {
        known: ["Published stratigraphic ranges place the exact taxa in overlapping lower Hell Creek intervals."],
        reconstructed: ["Exact spacing, colors, channel geometry, vegetation, weather, walking direction, and simultaneous presence."],
        boundary: "This is an overlap-window visualization, not evidence of an exact shared locality, direct meeting, herd, or partnership.",
      },
      evidence: [
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4104892/", use: "Triceratops stratigraphic distribution in the Hell Creek Formation" },
        { url: "https://doi.org/10.2110/palo.2017.060", use: "Edmontosaurus-bearing lower Hell Creek stratigraphic context" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; project-owned taxon identity assets only; external evidence was not used as artwork input.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/triceratops-horridus",
        promptRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/triceratops-horridus/prompt",
        correctionPromptRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/triceratops-horridus/correctionPrompt",
        prompt: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/triceratops-horridus/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image followed by Edmontosaurus limb-readability correction",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass after Edmontosaurus limb correction; neither animal is representative-eligible from this scene." },
        ecology: { status: "supported", note: "Approximate lower-formation overlap is supported; exact meeting and social behavior are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "parasaurolophus-centrosaurus-lower-dinosaur-park",
      timeBinId: "late-cretaceous",
      sceneType: "coexistence",
      title: "숲길 깊이층의 파라사우롤로푸스와 센트로사우루스",
      summary: "낮은 숲 카메라와 S자 길, 가로지른 통나무를 이용해 두 종을 서로 다른 깊이층에 놓은 지층 공존 가설입니다.",
      asset: {
        src: "assets/dinosaurs/parasaurolophus-walkeri-centrosaurus-forest-scurve-portrait-ecology-imagegen-v3.png",
        width: 1003,
        height: 1568,
        bytes: 3256137,
        sha256: "cdd22717e91c448494cb80237e486ad3e1e2167b81e45782cb32d6725862e13d",
        orientation: "portrait",
      },
      formation: {
        name: "Dinosaur Park Formation",
        context: "lower stratigraphic interval; formation-level reconstruction with no exact shared locality or direct meeting",
        ageRangeMa: { older: 76.9, younger: 76.5 },
        resolution: "approximate lower-formation overlap window; not an exact shared fossil horizon",
      },
      participants: [
        { taxonId: "parasaurolophus-walkeri", scientificName: "Parasaurolophus walkeri", role: "focal", certainty: "lower-formation overlap: moderate" },
        { taxonId: "centrosaurus-apertus", scientificName: "Centrosaurus apertus", role: "context", certainty: "lower-formation overlap: moderate" },
      ],
      compositionKey: "portrait-low-forest-scurve-zdepth",
      compositionLabel: "낮은 숲길 S자 Z심도",
      composition: {
        key: "portrait-low-forest-scurve-zdepth",
        label: "낮은 숲길 S자 Z심도",
        family: "foreground-framing",
        orientation: "portrait",
        camera: "low forest-floor view",
        spatialLayout: "Parasaurolophus crosses the lower-left path, a horizontal log divides the frame, and Centrosaurus occupies the upper-right terrace",
        diversityTags: ["low-camera", "s-curve-trail", "horizontal-log", "forest-frame", "z-depth"],
      },
      epistemic: {
        known: ["Published stratigraphic ranges overlap for the exact taxa in the lower Dinosaur Park Formation."],
        reconstructed: ["Exact spacing, colors, forest density, path, fallen log, sun shafts, walking direction, and simultaneous presence."],
        boundary: "The image visualizes a formation-range overlap only; it does not claim a shared locality, direct encounter, herd, or partnership.",
      },
      evidence: [
        { url: "https://rune.une.edu.au/web/handle/1959.11/27585", use: "Parasaurolophus walkeri stratigraphic position" },
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3933270/", use: "Centrosaurus apertus Dinosaur Park stratigraphic distribution" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; project-owned taxon identity assets only; external evidence was not used as artwork input.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/parasaurolophus-walkeri",
        promptRecord: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/parasaurolophus-walkeri/prompt",
        prompt: "tools/comfyui/lv1-portrait-coexistence-batch-20260803.json#records/parasaurolophus-walkeri/prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image after rejecting repeated river compositions and failed crowded forest attempts",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size S7 anatomy-review pass; exact small digits remain scene-scale limitations and the scene cannot become representative." },
        ecology: { status: "supported", note: "Approximate lower-formation overlap is supported; exact meeting and social behavior are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700, and 844x390: contain, loading, filters, scoped lightbox, touch zoom, focus, and history." },
        publication: { status: "published", note: "Anatomy, ecology, and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "protoceratops-juvenile-aggregation-djadokhta",
      timeBinId: "late-cretaceous",
      sceneType: "herd-growth",
      title: "사구 평원의 어린 프로토케라톱스 네 마리",
      summary: "가까이 보존된 네 어린 개체의 집합 근거를 서로 다른 방향으로 먹이를 찾는 장면으로 풀었습니다. 먼 작은 수각류는 종을 알 수 없는 복원 요소입니다.",
      asset: {
        src: "assets/dinosaurs/protoceratops-andrewsi-four-juvenile-aggregation-distant-theropod-herd-growth-imagegen-v1.png",
        width: 1024,
        height: 1536,
        bytes: 3093577,
        sha256: "f314971200009e363964880a659b21c7e5d89e8acc2a623c9d3b8b9a10d7f251",
        orientation: "portrait",
      },
      formation: {
        name: "Djadokhta Formation",
        context: "Tugrikin Shire juvenile aggregation context; the living spacing, terrain and distant small theropod are reconstructed",
        ageRangeMa: { older: 75.0, younger: 71.0 },
        resolution: "formation-scale approximate range; the four-individual fossil association does not preserve this living arrangement",
      },
      participants: [
        {
          taxonId: "protoceratops-andrewsi",
          scientificName: "Protoceratops andrewsi",
          role: "primary",
          certainty: "four-juvenile aggregation specimen: high; exact living spacing and behavior reconstructed",
        },
      ],
      compositionKey: "portrait-juvenile-arc-horizon-separated-context",
      compositionLabel: "유체 호형 배치와 먼 지평선",
      composition: {
        key: "portrait-juvenile-arc-horizon-separated-context",
        label: "유체 호형 배치와 먼 지평선",
        family: "nearfield-arc-depth",
        orientation: "portrait",
        camera: "low-to-moderate field-observation portrait with deep horizon",
        spatialLayout: "four juveniles form a loose asymmetric lower-field arc, an open path rises through the center-right, and one unidentified small theropod remains isolated in the upper-left far midground",
        diversityTags: ["juvenile-arc", "deep-horizon", "open-corridor", "separated-context"],
      },
      epistemic: {
        known: ["A published specimen preserves four similarly sized juvenile Protoceratops andrewsi in close association."],
        reconstructed: ["Living spacing, foraging poses, color, vegetation, weather and the unidentified distant small theropod."],
        boundary: "The aggregation does not establish siblings, parents, a permanent herd, coordinated defense, an attack or a Velociraptor identification for the distant animal.",
      },
      displayEpistemic: {
        known: ["네 마리의 어린 프로토케라톱스가 가까이 보존된 화석이 발견됐어요."],
        reconstructed: ["살아 있을 때의 간격, 먹이를 찾는 자세, 색과 풍경, 먼 작은 수각류는 상상해 복원했어요."],
        boundary: "네 마리가 가족이었거나 늘 무리 지어 살았다는 뜻은 아니며, 먼 동물의 정확한 종과 공격·방어 행동도 알 수 없습니다.",
        context: "어린 개체 집합 화석을 바탕으로 한 성장 장면",
        participantHeading: "근거가 있는 동물",
      },
      evidence: [
        { url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0113306", use: "four associated juvenile Protoceratops and limits on permanent-sociality inference" },
        { url: "https://www.amnh.org/explore/ology/ology-cards/038-fighting-dinosaurs", use: "Djadokhta fauna context only; not identification of the distant silhouette" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation; project-owned references only; the distant theropod is intentionally left unidentified.",
        license: "Generated project asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/protoceratops-juvenile-aggregation-ecosystem-scene-20260803.json#",
        promptRecord: "tools/comfyui/protoceratops-juvenile-aggregation-ecosystem-scene-20260803.json#prompt",
        prompt: "tools/comfyui/protoceratops-juvenile-aggregation-ecosystem-scene-20260803.json#prompt",
        seed: "not exposed by generator",
        workflow: "prompt-to-image after composition, animal-count and species-label review; distant theropod downgraded to unidentified context",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Original-size review passed for exactly four separated juvenile Protoceratops; the distant theropod is not taxonomically identified." },
        ecology: { status: "supported", note: "The four-juvenile association is supported; family, permanent-herd, defense, attack and exact distant-taxon claims are excluded." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x900, 390x844, 320x700 and 844x390: decode, contain, no horizontal overflow, filters, scoped lightbox, tap-hide and image-only pinch regression." },
        publication: { status: "published", note: "Anatomy, ecology, composition, label boundary and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "tyrannosaurus-edmontosaurus-kpg-dim-sky",
      timeBinId: "late-cretaceous",
      sceneType: "environment-event",
      title: "충돌 뒤 흐려지는 헬크리크의 하늘",
      summary: "상부 헬크리크의 두 동물을 충돌 뒤 대기 먼지로 햇빛이 약해지는 교육용 환경 장면에 멀리 분리해 놓았습니다. 같은 순간·장소나 서로의 반응은 확인되지 않습니다.",
      asset: {
        src: "assets/dinosaurs/tyrannosaurus-rex-edmontosaurus-annectens-kpg-dim-sky-separated-context-imagegen-v1.png",
        width: 1122,
        height: 1402,
        bytes: 1950997,
        sha256: "da07f508ff58d26a9323f3b54de5fd74fcca48c300c85bf6e1053398f54f3ad6",
        orientation: "portrait",
      },
      formation: {
        name: "Upper Hell Creek Formation, generalized floodplain",
        context: "northern inland fauna and post-Chicxulub atmospheric effects combined as an educational reconstruction; not a witnessed scene",
        ageRangeMa: { older: 66.04, younger: 66.0 },
        resolution: "upper-formation fauna plus post-impact atmospheric evidence and models; exact day, site, spacing and survival interval unresolved",
      },
      participants: [
        {
          taxonId: "edmontosaurus-annectens",
          scientificName: "Edmontosaurus annectens",
          role: "formation-fauna",
          certainty: "late Maastrichtian Hell Creek taxon: high; exact boundary-day individual and placement hypothetical",
        },
        {
          taxonId: "tyrannosaurus-rex",
          scientificName: "Tyrannosaurus rex",
          role: "formation-fauna",
          certainty: "upper Hell Creek occurrence: high; exact boundary-day individual and placement hypothetical",
        },
      ],
      compositionKey: "portrait-lowupward-kpg-skyfield-separated-fauna",
      compositionLabel: "낮은 지평선과 거대한 먼지 하늘",
      composition: {
        key: "portrait-lowupward-kpg-skyfield-separated-fauna",
        label: "낮은 지평선과 거대한 먼지 하늘",
        family: "skyfield-negative-space",
        orientation: "portrait",
        camera: "extremely low upward-looking portrait with the horizon confined to the lower quarter",
        spatialLayout: "a dim particulate sky fills roughly seventy percent of the frame while one small Edmontosaurus and one larger but still distant Tyrannosaurus occupy separate lower zones on outward-facing axes",
        diversityTags: ["sky-dominant", "low-horizon", "outward-axis", "asymmetric-void"],
      },
      epistemic: {
        known: [
          "Upper Hell Creek surveys record Tyrannosaurus and Edmontosaurus in the late Maastrichtian fauna.",
          "The Chicxulub impact injected fine dust and other aerosols that reduced sunlight and drove severe post-impact climate change.",
        ],
        reconstructed: [
          "The exact animals, shared place, spacing, poses, amber sky color, visible sun, dust density and moment after impact are reconstructed.",
          "Combining upper Hell Creek fauna with a generalized post-impact atmosphere in one frame is an educational compression, not a direct observation.",
        ],
        boundary: "The pale disc is the obscured Sun, not the impactor. The scene does not show the impact site, a chase, shared escape, immediate extinction, or proof that these two individuals experienced this exact sky together.",
      },
      displayEpistemic: {
        known: [
          "상부 헬크리크에서는 티라노사우루스와 에드몬토사우루스 화석이 알려져 있어요.",
          "약 6,600만 년 전 충돌은 대기에 먼지와 여러 입자를 퍼뜨려 햇빛과 기후를 크게 바꾸었어요.",
        ],
        reconstructed: [
          "두 공룡이 같은 장소에서 이 하늘을 보았는지, 하늘색·먼지량·태양의 모습과 이동 방향은 상상해 복원했어요.",
        ],
        boundary: "화면의 둥근 빛은 흐린 태양이고 운석이 아닙니다. 두 동물은 서로 쫓거나 함께 도망치는 모습이 아니며, 충돌 뒤 정확히 언제 이런 하늘이 보였는지도 알 수 없어요.",
        context: "충돌 뒤 대기 변화를 한 장에 압축한 환경 복원",
        participantHeading: "당시 헬크리크에서 알려진 동물",
      },
      evidence: [
        { url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0016574", use: "upper Hell Creek census including Tyrannosaurus and Edmontosaurus" },
        { url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0025186", use: "late Maastrichtian Edmontosaurus annectens taxonomic context" },
        { url: "https://www.nature.com/articles/s41561-023-01290-4", use: "fine silicate dust and modeled post-impact darkness and cooling" },
        { url: "https://www.nature.com/articles/s41586-022-04446-1", use: "timing and separation of immediate impact effects from the following impact winter" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation using only project-owned taxon references and a project-generated composition source; no external artwork pixels used.",
        license: "Generated project asset; distribution follows project and image-generation account terms. Research sources support factual claims only and are not image references.",
        metadataRecord: "tools/comfyui/kpg-dim-sky-ecosystem-scene-20260803.json#",
        promptRecord: "tools/comfyui/kpg-dim-sky-ecosystem-scene-20260803.json#prompts/source",
        correctionPromptRecord: "tools/comfyui/kpg-dim-sky-ecosystem-scene-20260803.json#prompts/correction",
        prompt: "tools/comfyui/kpg-dim-sky-ecosystem-scene-20260803.json#prompts/source",
        seed: "not exposed by generator",
        workflow: "prompt-to-image followed by local content correction; Triceratops removed after upper-Hell-Creek taxonomic audit",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Independent original-size scene-scale review passed exactly one Edmontosaurus and one Tyrannosaurus with no extra or fused bodies; small digits remain non-diagnostic." },
        ecology: { status: "supported", note: "Upper Hell Creek fauna and post-impact atmospheric effects are evidence-based, while the shared scene, behavior, sky color and timing are explicitly reconstructed." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x1000, 390x844, 320x700 and 844x390: card/lightbox decode, contain, no overflow, isolated filtering, tap-hide and image-only pinch." },
        publication: { status: "published", note: "Anatomy, ecology, composition, label-boundary and responsive gates are supported; representative promotion remains prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "dewars-farm-sauropod-theropod-crossing-trackways",
      timeBinId: "middle-jurassic",
      sceneType: "trace-evidence",
      title: "듀어스 팜의 교차 발자국길 구조 복원",
      summary: "보고된 네 용각류형 발자국길과 한 대형 수각류형 발자국길의 교차 구조를 위에서 본 학습 장면으로 다시 만들었습니다.",
      asset: {
        src: "assets/dinosaurs/cetiosaurus-oxoniensis-megalosaurus-bucklandii-analogue-crossing-trackways-trace-evidence-imagegen-hybrid-v2.png",
        width: 1672,
        height: 941,
        bytes: 3974514,
        sha256: "8a17fd2fb9bee5e2fdf9748c574abc7945baa9911f9ff0eda6ade98c3903d036",
        orientation: "landscape",
      },
      formation: {
        name: "Dewars Farm Quarry tracksite",
        context: "Oxfordshire Middle Jurassic limestone quarry; this educational plate is not a photogrammetric map or measured print tracing",
        ageRangeMa: { older: 168.0, younger: 166.0 },
        resolution: "site-level four-plus-one crossing pattern; exact trackmaker, coordinates, stride, order and time interval remain unresolved",
      },
      participants: [
        {
          taxonId: "cetiosaurus-oxoniensis",
          scientificName: "Cetiosaurus oxoniensis",
          role: "trackmaker-analogue",
          certainty: "regional sauropod body-plan comparison: moderate; exact genus and species unresolved",
        },
        {
          taxonId: "megalosaurus-bucklandii",
          scientificName: "Megalosaurus bucklandii",
          role: "trackmaker-analogue",
          certainty: "regional large-theropod comparison: moderate; exact genus and species unresolved",
        },
      ],
      compositionKey: "landscape-orthographic-naturalized-crossing-trackways",
      compositionLabel: "수직 조감 비주기 교차 흔적",
      composition: {
        key: "landscape-orthographic-naturalized-crossing-trackways",
        label: "수직 조감 비주기 교차 흔적",
        family: "evidence-led-plan-view",
        orientation: "landscape",
        camera: "strict overhead orthographic evidence view",
        spatialLayout: "four nonperiodic two-rail sauropod corridors vary in stride, width, phase, heading, depth and partial preservation while one coherent nine-print tridactyl route crosses through separated gaps",
        diversityTags: ["orthographic", "trace-only", "controlled-irregularity", "partial-preservation", "diagonal-crossing"],
      },
      epistemic: {
        known: ["Four sauropod-type trackways and one crossing large-theropod-type trackway were reported at Dewars Farm."],
        reconstructed: ["Exact print shapes, depths, intervals, wetness, lighting and the plan-view arrangement are an educational reconstruction."],
        boundary: "Cetiosaurus and Megalosaurus are regional comparison analogues, not exact trackmakers; crossing does not establish simultaneity, chase, hunting, herd movement or track order.",
      },
      displayEpistemic: {
        known: ["현장에서는 용각류형 발자국길 네 줄과 이를 가로지르는 큰 수각류형 발자국길 한 줄이 보고됐어요."],
        reconstructed: ["발자국의 정확한 모양과 깊이, 간격, 진흙의 물기와 화면 배치는 학습용으로 다시 만들었어요."],
        boundary: "케티오사우루스와 메갈로사우루스는 비교 후보일 뿐 정확한 발자국 주인이 아니며, 서로 같은 순간에 만나거나 쫓았다는 뜻도 아닙니다.",
        context: "발자국길 구조를 읽는 흔적 증거 복원",
        participantHeading: "발자국 주인 비교 후보",
      },
      traceEvidence: {
        bodiesShown: false,
        exactTaxonClaim: false,
        simultaneousCrossingClaim: false,
        interactionClaim: false,
      },
      evidence: [
        { url: "https://www.ox.ac.uk/news/2025-01-02-major-new-footprint-discoveries-britain-s-dinosaur-highway", use: "Dewars Farm four sauropod and one crossing large-theropod trackway report" },
        { url: "https://www.ox.ac.uk/news/2026-06-25-return-to-the-dinosaur-highway", use: "updated Oxford account and cautious regional trackmaker comparisons" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation for the empty mud plus a project-authored fixed-seed SVG/Sharp v2 topology overlay; no external artwork or site-photo pixels used.",
        license: "Generated and project-authored hybrid asset; distribution follows project and image-generation account terms. No third-party artwork license is asserted.",
        metadataRecord: "tools/comfyui/middle-jurassic-dewars-crossing-trackways-ecosystem-scene-20260807-v2.json#",
        promptRecord: "tools/comfyui/middle-jurassic-dewars-crossing-trackways-ecosystem-scene-20260807-v2.json#prompt",
        correctionPromptRecord: "tools/comfyui/middle-jurassic-dewars-crossing-trackways-ecosystem-scene-20260807-v2.json#overlayWorkflow",
        prompt: "tools/comfyui/middle-jurassic-dewars-crossing-trackways-ecosystem-scene-20260807-v2.json#prompt",
        seed: "background:not-exposed; authored-layout:2026080701",
        workflow: "hybrid evidence reconstruction: generated empty mud with fixed-seed, nonperiodic project-authored trace topology overlay",
        generator: "OpenAI built-in image generation plus project-authored SVG/Sharp v2 compositor",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "No dinosaur bodies are shown; independent review passed the four two-rail sauropod corridors and one nine-print tridactyl trail as trace topology only." },
        ecology: { status: "supported", note: "The reported four-plus-one crossing pattern is supported; exact makers, measurements, simultaneity, behavior and order are excluded." },
        responsive: { status: "supported", note: "2026-08-07 root QA passed at 1440x1000 and 390x844: the v2 asset decoded at 1672x941, used contain without horizontal overflow, and retained readable nonperiodic routes at card size." },
        publication: { status: "published", note: "V2 trace topology, controlled-irregularity metrics, evidence boundary, composition and responsive gates are supported; representative and exact-trackmaker promotion remain prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
    {
      id: "eoraptor-chromogisaurus-cancha-de-bochas-weathered-ash-bank",
      timeBinId: "late-triassic",
      sceneType: "environment-event",
      title: "풍화된 화산재 띠가 드러난 칸차 데 보차스 층서 풍경",
      summary: "같은 칸차 데 보차스 층원에서 알려졌지만 같은 뼈층에서 함께 나온 것은 확인되지 않은 에오랍토르와 크로모기사우루스를, 풍화되어 끊긴 오래된 화산재성 층이 드러난 가상 단면에 배치했습니다. 밝은 띠는 현재 분화나 내리는 화산재가 아니며, 같은 순간·같은 노두·직접 조우를 뜻하지 않습니다.",
      asset: {
        src: "assets/dinosaurs/eoraptor-lunensis-chromogisaurus-cancha-de-bochas-weathered-ash-bank-stratigraphic-context-imagegen-v1.png",
        width: 1672,
        height: 941,
        bytes: 3281881,
        sha256: "e140b999fd1c6c5c7e1f8be1962d96e1f0d68156caff28db7ef0ea4f590108bb",
        orientation: "landscape",
      },
      formation: {
        name: "Ischigualasto Formation, Cancha de Bochas Member",
        context: "same-member stratigraphic comparison with a generalized weathered tuffaceous or altered-ash exposure; not a literal fossil outcrop or shared bed",
        ageRangeMa: { older: 233.0, younger: 225.0 },
        resolution: "same member only; exact bed, outcrop, relative age, animal positions and shared moment unresolved",
      },
      participants: [
        {
          taxonId: "eoraptor-lunensis",
          scientificName: "Eoraptor lunensis",
          role: "near-field stratigraphic comparison",
          certainty: "Cancha de Bochas Member occurrence high; exact bed and depicted position unsupported",
        },
        {
          taxonId: "chromogisaurus-novasi",
          scientificName: "Chromogisaurus novasi",
          role: "distant stratigraphic comparison",
          certainty: "Cancha de Bochas Member occurrence high; exact bed and depicted position unsupported; skull, neck and hand are comparative reconstruction",
        },
      ],
      compositionKey: "landscape-raking-bankface-weathered-ash-lenses",
      compositionLabel: "침식 제방을 비껴 읽는 풍화 지층",
      composition: {
        key: "landscape-raking-bankface-weathered-ash-lenses",
        label: "침식 제방을 비껴 읽는 풍화 지층",
        family: "geology-led-lateral-section",
        orientation: "landscape",
        camera: "low lateral raking view along a natural eroded bankface with the horizon constrained to the upper 15 percent",
        spatialLayout: "the weathered bankface fills the left and center, low-contrast altered-ash lenses cross the middle with erosion gaps, one Eoraptor occupies the lower-right middle ground, and one much smaller Chromogisaurus stands on a separate upper-right shelf beyond a shadowed notch",
        diversityTags: ["geology-dominant", "lateral-section", "horizontal-strata", "same-direction-depth-discovery"],
      },
      epistemic: {
        known: [
          "Both named taxa are documented from the Cancha de Bochas Member, but no shared fossil bed or direct association is established.",
          "Stratigraphic work documents altered volcanic-ash, bentonitic or tuffaceous horizons within the member.",
        ],
        reconstructed: [
          "Exact outcrop shape, exposed-band thickness, color and continuity, erosional relief, animal positions, simultaneous life appearance, weather and vegetation are reconstructed.",
        ],
        boundary: "The weathered band is a generalized older lithified tuffaceous or ash-bearing horizon exposed by erosion, not an active eruption, falling ash, or proof that either taxon occurs on that exact bed. The combined frame is a same-member stratigraphic comparison and does not claim the same moment, locality, encounter, interaction, ancestor-descendant relation, or shared response.",
      },
      displayEpistemic: {
        known: [
          "에오랍토르와 크로모기사우루스는 모두 칸차 데 보차스 층원에서 알려졌지만, 같은 뼈층에서 함께 나온 것은 확인되지 않았어요.",
          "이 층원에는 오래된 화산재가 변질된 응회질·벤토나이트성 지층 기록이 남아 있어요.",
        ],
        reconstructed: [
          "노두 모양과 밝은 띠의 두께·색·끊김, 침식 지형, 두 동물의 위치와 색, 같은 화면의 순간, 날씨와 식생은 학습용으로 복원했어요.",
        ],
        boundary: "같은 층원에서 알려졌지만 같은 뼈층에서 함께 나온 것은 확인되지 않은 두 동물을, 풍화되어 끊긴 오래된 화산재성 층이 드러난 가상 단면에 배치한 층서 비교 복원입니다. 밝은 띠는 현재 분화나 내리는 화산재가 아니며, 같은 순간·같은 노두·직접 조우를 뜻하지 않습니다.",
        context: "오래된 화산재성 지층을 읽는 층서 비교 복원",
        participantHeading: "같은 층원 비교 동물",
      },
      evidence: [
        { url: "https://doi.org/10.1016/j.jsames.2008.10.004", use: "formation architecture, overbank and paleosol context, and altered-ash or tuffaceous horizons" },
        { url: "https://doi.org/10.1080/14772019.2010.484650", use: "Chromogisaurus Cancha de Bochas occurrence and incomplete postcranial evidence boundary" },
        { url: "https://doi.org/10.1080/02724634.2013.820113", use: "Eoraptor redescription and Cancha de Bochas context" },
        { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3088398/", use: "member fauna and stratigraphic context without a shared-bed claim" },
      ],
      provenance: {
        sourceAttribution: "OpenAI built-in image generation using four project-owned taxon references for anatomy and identity only, followed by a targeted correction using the project-generated first candidate; no external artwork or paper-figure pixels used.",
        license: "Generated project asset; distribution follows project and image-generation account terms. Research sources support factual constraints only and are not image references.",
        metadataRecord: "tools/comfyui/triassic-ischigualasto-weathered-ash-bank-ecosystem-scene-20260803.json#",
        promptRecord: "tools/comfyui/triassic-ischigualasto-weathered-ash-bank-ecosystem-scene-20260803.json#prompts/source",
        correctionPromptRecord: "tools/comfyui/triassic-ischigualasto-weathered-ash-bank-ecosystem-scene-20260803.json#prompts/correction",
        prompt: "tools/comfyui/triassic-ischigualasto-weathered-ash-bank-ecosystem-scene-20260803.json#prompts/source",
        seed: "not exposed by generator",
        workflow: "prompt-to-image with four anatomy-only project references followed by a layer-only correction; independent anatomy, ecology, composition and age-safety review",
        generator: "OpenAI built-in image generation",
      },
      representativeEligible: false,
      gates: {
        anatomy: { status: "supported", note: "Independent original-size scene-scale review passed exactly one Eoraptor and one Chromogisaurus with paired forelimbs, paired hind limbs and one continuous tail each; small digits and distant Chromogisaurus details remain non-diagnostic." },
        ecology: { status: "supported", note: "Same-member occurrence and altered-ash-bearing stratigraphy are supported; the public card explicitly excludes a shared bed, outcrop, moment, eruption, encounter or interaction." },
        responsive: { status: "supported", note: "2026-08-03 root QA passed at 1440x1000, 390x844, 320x700 and 844x390: 1672x941 card/lightbox decode, contain, no overflow, isolated filtering, authored public boundary, distinct Korean composition tags, tap-hide and image-only pinch." },
        publication: { status: "published", note: "Anatomy, ecology, composition, age-safety and responsive gates are supported; the same-member boundary is public and representative promotion is prohibited." },
      },
      publication: { status: "published", eligible: true },
    },
  ],
};
