// Evidence-gated motion pilots. This lane is intentionally separate from
// generatedImageSamples and gallery slots: no entry here can replace a still
// representative or become anatomy evidence.
window.motionSampleCatalog = {
  schemaVersion: 1,
  policy: {
    tier: "M0",
    scope: "environment-only ambient motion over a fixed approved still",
    representativePromotion: "prohibited",
    galleryPromotion: "prohibited",
    autoplay: "prohibited",
    biologicalMotion: "prohibited in M0",
    sceneRoles: ["solo", "ecology-activity", "interspecies-interaction"],
    publicRequires: ["motion", "responsive", "publication"],
    accessibility: "explicit click-to-play, muted, playsinline, poster fallback, reduced-motion and save-data aware",
  },
  samples: [
    {
      id: "yutyrannus-huali-cold-breath-ambient-m0-v1",
      title: "흰 유티란누스의 찬 숨",
      taxonId: "yutyrannus-huali",
      scientificName: "Yutyrannus huali",
      tier: "M0",
      motionClass: "environment-only",
      sceneRole: "solo",
      sceneRoleLabel: "단독 개체",
      motionLabel: "입 주변 찬 수증기",
      description: "공룡 몸체와 해부학 픽셀은 고정하고, 입 주변의 짧은 찬 숨결만 움직이는 5초 환경 연출 시험입니다.",
      poster: "assets/dinosaurs/yutyrannus-huali-yixian-white-mottled-feathered-representative-imagegen-v1.png",
      src: "assets/motion/yutyrannus-huali-white-feather-cold-breath-ambient-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-pilot-batch-20260803.json#/samples/yutyrannus-huali-cold-breath-ambient-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "Motion cannot be used to upgrade the still image's anatomy verdict." },
        motion: { status: "supported", note: "Two localized leftward breath pulses are visible at 390px while the protected body region remains static; significant-change energy inside the breath zone is 99.11%." },
        responsive: { status: "supported", note: "Click-to-play, muted playback, poster fallback, and containment passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 environment-only pilot passed file, motion-locality, responsive, accessibility, and provenance gates on 2026-08-03." },
      },
      file: { sha256: "501c7fedc826ce49f97c687ff98250d63c0d66551024fbf651e215c38dbcdc3e", bytes: 278194, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
    {
      id: "tyrannosaurus-rex-ground-mist-ambient-m0-v1",
      title: "티라노사우루스의 지면 안개",
      taxonId: "tyrannosaurus-rex",
      scientificName: "Tyrannosaurus rex",
      tier: "M0",
      motionClass: "environment-only",
      sceneRole: "solo",
      sceneRoleLabel: "단독 개체",
      motionLabel: "낮게 흐르는 지면 안개",
      description: "공룡은 움직이지 않고, 헬크릭 지면의 얕은 안개만 천천히 흐르는 5초 환경 연출 시험입니다.",
      poster: "assets/dinosaurs/tyrannosaurus-rex-hell-creek-deepskull-twofinger-representative-imagegen-v1.png",
      src: "assets/motion/tyrannosaurus-rex-hell-creek-ground-mist-ambient-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-pilot-batch-20260803.json#/samples/tyrannosaurus-rex-ground-mist-ambient-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "Motion cannot be used to upgrade the still image's anatomy verdict." },
        motion: { status: "supported", note: "Low mist stays in the right foreground away from the dinosaur; protected pixels remain static and 99.59% of significant-change energy stays inside the mist zone." },
        responsive: { status: "supported", note: "Click-to-play, muted playback, poster fallback, and containment passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 environment-only pilot passed file, motion-locality, responsive, accessibility, and provenance gates on 2026-08-03." },
      },
      file: { sha256: "d117470c403e29c2f2d394277e1e3ccf155cea23557ae2340004cf0bfd5309c7", bytes: 220780, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
    {
      id: "brachiosaurus-altithorax-skylight-ambient-m0-v1",
      title: "브라키오사우루스의 움직이는 하늘빛",
      taxonId: "brachiosaurus-altithorax",
      scientificName: "Brachiosaurus altithorax",
      tier: "M0",
      motionClass: "environment-only",
      sceneRole: "solo",
      sceneRoleLabel: "단독 개체",
      motionLabel: "느린 하늘빛과 옅은 대기",
      description: "높은 어깨와 둥근 비강 융기·높은 콧구멍 단서는 고정하고, 하늘빛과 옅은 대기만 움직이는 5초 시험입니다.",
      poster: "assets/dinosaurs/brachiosaurus-altithorax-nasal-mound-fullbody-imagegen-v18.png",
      src: "assets/motion/brachiosaurus-altithorax-high-shoulder-skylight-ambient-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-pilot-batch-20260803.json#/samples/brachiosaurus-altithorax-skylight-ambient-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "High shoulders and the nasal mound remain inherited from the fixed poster; motion supplies no anatomy evidence." },
        motion: { status: "supported", note: "Slow sky-light stays above and right of the neck; the nasal mound and high-shouldered body are untouched, with 99.65% of significant-change energy inside the sky zone." },
        responsive: { status: "supported", note: "Click-to-play, muted playback, poster fallback, and containment passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 environment-only pilot passed file, motion-locality, responsive, accessibility, and provenance gates on 2026-08-03." },
      },
      file: { sha256: "1fc75a90a54d9c497afdc9892f27041dbad246d7d0fc2dc7acb8efc11c3f3362", bytes: 307698, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
    {
      id: "psittacosaurus-mongoliensis-water-shimmer-solo-m0-v1",
      title: "프시타코사우루스와 잔물결",
      taxonId: "psittacosaurus-mongoliensis",
      scientificName: "Psittacosaurus mongoliensis",
      tier: "M0",
      motionClass: "environment-only",
      sceneRole: "solo",
      sceneRoleLabel: "단독 개체",
      motionLabel: "몸 뒤쪽 얕은 물의 반사광",
      description: "꼬리 강모가 보이는 단독 개체는 완전히 고정하고, 오른쪽 뒤 물웅덩이의 잔잔한 반사광만 움직이는 5초 시험입니다. 강모는 속 수준의 참고 단서이며 종의 필수 특징으로 단정하지 않습니다.",
      poster: "assets/dinosaurs/psittacosaurus-mongoliensis-genus-tail-bristle-anatomy-imagegen-v1.png",
      src: "assets/motion/psittacosaurus-mongoliensis-tail-bristle-water-shimmer-solo-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-scene-role-batch-20260803.json#/samples/psittacosaurus-mongoliensis-water-shimmer-solo-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "The S7 genus-level bristle-reference verdict is inherited; motion supplies no species-level anatomy evidence." },
        motion: { status: "supported", note: "Fixed-animal and water-layer locality checks passed; significant change is 99.57% inside the water-reflection zone." },
        responsive: { status: "supported", note: "Click-to-play, muted inline playback, poster fallback, role labels, card containment, and no horizontal overflow passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 scene-role sample passed file, motion-locality, responsive, accessibility, provenance, and evidence-boundary gates on 2026-08-03." },
      },
      file: { sha256: "a6a9be69e7323ff3357267daf576aacb109d0adf68978bc40904948a9680e21c", bytes: 260005, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
    {
      id: "maiasaura-peeblesorum-nesting-ground-pollen-ecology-m0-v1",
      title: "마이아사우라 산란지의 바람",
      taxonId: "maiasaura-peeblesorum",
      scientificName: "Maiasaura peeblesorum",
      tier: "M0",
      motionClass: "environment-only",
      sceneRole: "ecology-activity",
      sceneRoleLabel: "생태 활동",
      motionLabel: "성체와 둥지 사이 빈 지면의 씨앗·꽃가루",
      description: "성체·둥지·알은 고정하고 그 사이 빈 지면의 가벼운 씨앗과 꽃가루만 흐르는 5초 시험입니다. 산란지 근거를 보여 주되 실제 어미의 경비·급식·돌봄 행동으로 단정하지 않습니다.",
      poster: "assets/dinosaurs/maiasaura-peeblesorum-two-medicine-nesting-ground-egg-hypothesis-portrait-imagegen-v1.png",
      src: "assets/motion/maiasaura-peeblesorum-nesting-ground-pollen-ecology-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-scene-role-batch-20260803.json#/samples/maiasaura-peeblesorum-nesting-ground-pollen-ecology-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "The approved S3 anatomy-review and nesting-hypothesis boundary are inherited; motion adds no care-behavior evidence." },
        motion: { status: "supported", note: "Fixed-adult, fixed-egg, and middle-ground locality checks passed; significant change is 99.53% inside the pollen zone." },
        responsive: { status: "supported", note: "Click-to-play, muted inline playback, poster fallback, role labels, card containment, and no horizontal overflow passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 scene-role sample passed file, motion-locality, responsive, accessibility, provenance, and evidence-boundary gates on 2026-08-03." },
      },
      file: { sha256: "13886af1a329ead6497f40a0e2a947bbfdc3b3ab0ab3aa367683af8dfc30f972", bytes: 176226, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
    {
      id: "velociraptor-protoceratops-dustfront-interaction-m0-v1",
      title: "먼지 전선 앞의 두 공룡",
      taxonId: "velociraptor-mongoliensis",
      companionTaxonIds: ["protoceratops-andrewsi"],
      scientificName: "Velociraptor mongoliensis · Protoceratops andrewsi",
      tier: "M0",
      motionClass: "environment-only",
      sceneRole: "interspecies-interaction",
      sceneRoleLabel: "다른 공룡과 상호작용",
      motionLabel: "두 개체 위쪽의 먼지 전선",
      description: "서로를 경계하는 두 공룡은 완전히 고정하고, 위쪽 먼지 전선만 천천히 흐르는 5초 시험입니다. 접촉·추격·공격이나 유명 화석의 정확한 자세를 재현하지 않습니다.",
      poster: "assets/dinosaurs/velociraptor-mongoliensis-protoceratops-standoff-ecology-imagegen-v1.png",
      src: "assets/motion/velociraptor-mongoliensis-protoceratops-dustfront-interaction-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-scene-role-batch-20260803.json#/samples/velociraptor-protoceratops-dustfront-interaction-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "The approved S5 interaction-scene anatomy review is inherited; the motion adds no identity evidence." },
        motion: { status: "supported", note: "Fixed-two-animal and upper-dust locality checks passed; significant change is 99.60% inside the dust-front zone." },
        responsive: { status: "supported", note: "Click-to-play, muted inline playback, poster fallback, role labels, card containment, and no horizontal overflow passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 scene-role sample passed file, motion-locality, responsive, accessibility, provenance, and evidence-boundary gates on 2026-08-03." },
      },
      file: { sha256: "ae04113adc19e592cc9b808054b2607bc9a3e9e15aa9beb9b3a8f6d85b3acff2", bytes: 280640, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
  ],
};
