// Evidence-gated motion pilots. This lane is intentionally separate from
// generatedImageSamples and gallery slots: no entry here can replace a still
// representative or become anatomy evidence.
window.motionSampleCatalog = {
  schemaVersion: 1,
  policy: {
    tier: "M0",
    scope: "environment-only ambient motion over a fixed approved still",
    representativePromotion: "prohibited",
    galleryPromotion: "prohibited",
    autoplay: "prohibited",
    publicRequires: ["motion", "responsive", "publication"],
    accessibility: "explicit click-to-play, muted, playsinline, poster fallback, reduced-motion and save-data aware",
  },
  samples: [
    {
      id: "yutyrannus-huali-cold-breath-ambient-m0-v1",
      title: "흰 유티란누스의 찬 숨",
      taxonId: "yutyrannus-huali",
      scientificName: "Yutyrannus huali",
      tier: "M0",
      motionClass: "environment-only",
      motionLabel: "입 주변 찬 수증기",
      description: "공룡 몸체와 해부학 픽셀은 고정하고, 입 주변의 짧은 찬 숨결만 움직이는 5초 환경 연출 시험입니다.",
      poster: "assets/dinosaurs/yutyrannus-huali-yixian-white-mottled-feathered-representative-imagegen-v1.png",
      src: "assets/motion/yutyrannus-huali-white-feather-cold-breath-ambient-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-pilot-batch-20260803.json#/samples/yutyrannus-huali-cold-breath-ambient-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "Motion cannot be used to upgrade the still image's anatomy verdict." },
        motion: { status: "supported", note: "Two localized leftward breath pulses are visible at 390px while the protected body region remains static; significant-change energy inside the breath zone is 99.11%." },
        responsive: { status: "supported", note: "Click-to-play, muted playback, poster fallback, and containment passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 environment-only pilot passed file, motion-locality, responsive, accessibility, and provenance gates on 2026-08-03." },
      },
      file: { sha256: "501c7fedc826ce49f97c687ff98250d63c0d66551024fbf651e215c38dbcdc3e", bytes: 278194, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
    {
      id: "tyrannosaurus-rex-ground-mist-ambient-m0-v1",
      title: "티라노사우루스의 지면 안개",
      taxonId: "tyrannosaurus-rex",
      scientificName: "Tyrannosaurus rex",
      tier: "M0",
      motionClass: "environment-only",
      motionLabel: "낮게 흐르는 지면 안개",
      description: "공룡은 움직이지 않고, 헬크릭 지면의 얕은 안개만 천천히 흐르는 5초 환경 연출 시험입니다.",
      poster: "assets/dinosaurs/tyrannosaurus-rex-hell-creek-deepskull-twofinger-representative-imagegen-v1.png",
      src: "assets/motion/tyrannosaurus-rex-hell-creek-ground-mist-ambient-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-pilot-batch-20260803.json#/samples/tyrannosaurus-rex-ground-mist-ambient-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "Motion cannot be used to upgrade the still image's anatomy verdict." },
        motion: { status: "supported", note: "Low mist stays in the right foreground away from the dinosaur; protected pixels remain static and 99.59% of significant-change energy stays inside the mist zone." },
        responsive: { status: "supported", note: "Click-to-play, muted playback, poster fallback, and containment passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 environment-only pilot passed file, motion-locality, responsive, accessibility, and provenance gates on 2026-08-03." },
      },
      file: { sha256: "d117470c403e29c2f2d394277e1e3ccf155cea23557ae2340004cf0bfd5309c7", bytes: 220780, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
    {
      id: "brachiosaurus-altithorax-skylight-ambient-m0-v1",
      title: "브라키오사우루스의 움직이는 하늘빛",
      taxonId: "brachiosaurus-altithorax",
      scientificName: "Brachiosaurus altithorax",
      tier: "M0",
      motionClass: "environment-only",
      motionLabel: "느린 하늘빛과 옅은 대기",
      description: "높은 어깨와 둥근 비강 융기·높은 콧구멍 단서는 고정하고, 하늘빛과 옅은 대기만 움직이는 5초 시험입니다.",
      poster: "assets/dinosaurs/brachiosaurus-altithorax-nasal-mound-fullbody-imagegen-v18.png",
      src: "assets/motion/brachiosaurus-altithorax-high-shoulder-skylight-ambient-m0-v1.mp4",
      provenance: {
        metadataRecord: "tools/comfyui/motion-pilot-batch-20260803.json#/samples/brachiosaurus-altithorax-skylight-ambient-m0-v1",
        sourceLicense: "project-owned generated still",
        workflow: "fixed-still environmental overlay; no biological or anatomical animation",
      },
      representativeEligible: false,
      galleryEligible: false,
      review: {
        anatomy: { status: "poster-inherited", note: "High shoulders and the nasal mound remain inherited from the fixed poster; motion supplies no anatomy evidence." },
        motion: { status: "supported", note: "Slow sky-light stays above and right of the neck; the nasal mound and high-shouldered body are untouched, with 99.65% of significant-change energy inside the sky zone." },
        responsive: { status: "supported", note: "Click-to-play, muted playback, poster fallback, and containment passed at 1440x900, 390x844, and 844x390 on 2026-08-03." },
        publication: { status: "published", note: "M0 environment-only pilot passed file, motion-locality, responsive, accessibility, and provenance gates on 2026-08-03." },
      },
      file: { sha256: "1fc75a90a54d9c497afdc9892f27041dbad246d7d0fc2dc7acb8efc11c3f3362", bytes: 307698, width: 960, height: 640, durationSeconds: 5, fps: 24, codec: "h264" },
    },
  ],
};
