import json
from pathlib import Path


DINOSAURS = {
    "herrerasaurus-ischigualastensis": {
        "scientificName": "Herrerasaurus ischigualastensis",
        "period": "Late Triassic",
        "region": "South American semi-arid floodplain",
        "visualTraits": [
            "early saurischian predator",
            "slender bipedal body",
            "long narrow skull with sharp teeth",
            "short-to-medium neck with the head held forward",
            "long balancing tail",
            "long bent grasping forelimbs with visible clawed hands below the chest",
            "forelimbs clearly longer than tiny Tyrannosaurus-style arms",
            "light agile hind legs",
        ],
        "surface": "intact natural skin, fine subtle scales",
        "anatomyRules": {
            "mustHave": [
                "slender early dinosaur body",
                "long bent grasping forelimbs held below the chest",
                "visible clawed hands, not tiny tucked two-finger arms",
                "long narrow skull",
                "short-to-medium neck, not a sauropodomorph neck",
                "bipedal stance",
                "long balancing tail",
            ],
            "rejectIf": [
                "tyrannosaur giant head",
                "tiny two-finger tyrannosaur arms",
                "tiny tucked forelimbs",
                "forelimbs reduced to small Tyrannosaurus-like arms",
                "sauropod body plan",
                "sauropodomorph body plan",
                "long swan neck",
                "ostrich-like neck",
                "quadrupedal stance",
                "large dorsal plates",
                "horned ceratopsian head",
            ],
        },
    },
    "coelophysis-bauri": {
        "scientificName": "Coelophysis bauri",
        "period": "Late Triassic",
        "region": "North American dry river plain",
        "visualTraits": [
            "small slender early theropod",
            "very light narrow body",
            "long S-shaped neck",
            "small narrow skull",
            "long thin balancing tail",
            "long lean hind legs",
            "two small grasping forelimbs with visible three-fingered hands",
            "walking on dry ground, not perched on a branch",
        ],
        "surface": "intact natural skin, fine subtle scales",
        "anatomyRules": {
            "mustHave": [
                "small gracile body",
                "long thin neck",
                "small narrow skull",
                "long thin tail",
                "bipedal stance",
                "two small grasping forelimbs with three-fingered hands",
                "feet planted on dry ground",
            ],
            "rejectIf": [
                "bulky tyrannosaur body",
                "oversized head",
                "sauropod body plan",
                "quadrupedal stance",
                "armored back",
                "dorsal plates",
                "modern lizard body",
                "bird beak",
                "wing-like arms",
                "missing forelimbs",
                "perched on a log",
                "tree branch perch",
            ],
        },
    },
    "plateosaurus-engelhardti": {
        "scientificName": "Plateosaurus engelhardti",
        "period": "Late Triassic",
        "region": "European seasonal woodland",
        "visualTraits": [
            "large early sauropodomorph herbivore",
            "moderately long neck and small narrow herbivore head",
            "neck carried forward and low, not towering vertically",
            "long low toothless-looking herbivore snout with no exposed predator teeth",
            "closed mouth with no visible teeth",
            "deep elongated torso",
            "heavy rounded belly and robust herbivore hips",
            "strong tall hind limbs carrying most of the weight",
            "shorter forelimbs held off the ground with five-fingered grasping hands",
            "large visible thumb claws on the hands",
            "clear side-profile view, not rear view",
            "hind-limb-dominant stance with the forelimbs shorter and lighter than the rear legs",
            "front hands lifted close to the chest, not touching the ground",
            "obligate bipedal posture with two large hind legs and the tail balancing behind",
            "two large planted hind feet clearly carry the body",
            "long heavy tail held clear of the ground",
        ],
        "surface": "intact natural skin, subtle scales",
        "anatomyRules": {
            "mustHave": [
                "early sauropodomorph body plan, not a true giant sauropod",
                "moderately long neck",
                "small herbivore head",
                "long low herbivore snout with no visible sharp teeth",
                "closed mouth without exposed teeth",
                "deep rounded herbivore torso",
                "forelimbs shorter than the hind limbs",
                "large visible thumb claws on the hands",
                "five-fingered grasping hands held off the ground",
                "hind limbs larger and more column-like than forelimbs",
                "side-profile body, not rear view",
                "hind-limb-dominant bipedal posture",
                "two large planted hind feet carrying the body",
                "long heavy tail held off the ground",
            ],
            "rejectIf": [
                "theropod predator skull",
                "raptor-like predator body",
                "slender carnivorous theropod body",
                "large sharp predator teeth",
                "open toothy mouth",
                "open roaring mouth",
                "Tyrannosaurus body plan",
                "Allosaurus body plan",
                "short neck",
                "tiny tyrannosaur arms",
                "front feet as large as rear feet",
                "front hands planted like elephant feet",
                "front hands touching the ground",
                "weight-bearing forelimbs",
                "quadrupedal walking pose",
                "four feet equally planted on the ground",
                "four equal column legs",
                "four equal pillar legs",
                "rear view",
                "back view",
                "elephant-like sauropod legs",
                "fully quadrupedal giant sauropod stance",
                "fully quadrupedal sauropod stance",
                "true sauropod body plan",
                "Apatosaurus body",
                "Brachiosaurus body",
                "high-shouldered brachiosaur shape",
                "diplodocid whip tail body",
                "neck towering vertically over the shoulders",
                "tail dragging on the ground",
                "ceratopsian horns",
            ],
        },
    },
    "allosaurus-fragilis": {
        "scientificName": "Allosaurus fragilis",
        "period": "Late Jurassic",
        "region": "North American floodplain",
        "visualTraits": [
            "large Jurassic theropod predator",
            "long low skull with low brow ridges",
            "closed or slightly parted jaws, calm walking pose",
            "three-fingered forelimbs",
            "powerful hind legs",
            "balanced horizontal torso",
            "long muscular tail",
        ],
        "surface": "intact natural skin, subtle scales",
        "anatomyRules": {
            "forelimbDigitsPerHand": 3,
            "mustHave": [
                "long low theropod skull",
                "low brow ridges above the eyes",
                "closed or slightly parted jaws",
                "visible three-fingered forelimbs",
                "bipedal stance",
                "long balancing tail",
            ],
            "rejectIf": [
                "tiny two-finger tyrannosaur arms",
                "deep tyrannosaur skull",
                "wide open roaring mouth",
                "oversized gape",
                "monster-like teeth",
                "four or five fingers on a visible hand",
                "sauropod body plan",
                "quadrupedal stance",
                "horned ceratopsian head",
            ],
        },
    },
    "apatosaurus-ajax": {
        "scientificName": "Apatosaurus ajax",
        "period": "Late Jurassic",
        "region": "North American floodplain",
        "visualTraits": [
            "massive diplodocid sauropod body",
            "long low neck",
            "neck held forward and low, not vertical",
            "small head held forward",
            "very long whip-like tail",
            "tail held clear of the ground",
            "heavy quadrupedal stance",
            "front limbs not taller than hind limbs",
        ],
        "surface": "intact natural skin, subtle scales",
        "anatomyRules": {
            "mustHave": [
                "massive quadrupedal sauropod body",
                "long low neck",
                "neck held forward and low",
                "small head held forward",
                "very long whip-like tail",
                "tail held clear of the ground",
                "front limbs not taller than hind limbs",
            ],
            "rejectIf": [
                "short neck",
                "vertical swan neck",
                "neck rising straight up from the shoulders",
                "high-shouldered brachiosaur silhouette",
                "front limbs taller than hind limbs",
                "tail dragging on the ground",
                "theropod body plan",
                "bipedal stance",
                "predator skull",
            ],
        },
    },
    "tyrannosaurus-rex": {
        "scientificName": "Tyrannosaurus rex",
        "period": "Late Cretaceous",
        "region": "North American floodplain",
        "visualTraits": [
            "large deep skull",
            "very short two-fingered forelimbs held tight against the chest",
            "tiny forearms that do not reach below the belly",
            "small hands with exactly two blunt clawed fingers, not spread apart",
            "powerful hind legs",
            "long balancing tail",
            "bipedal theropod posture",
        ],
        "surface": "intact natural skin, subtle scales",
        "anatomyRules": {
            "forelimbDigitsPerHand": 2,
            "mustHave": [
                "each visible hand has exactly two fingers",
                "very short two-fingered forelimbs held close to the ribs",
                "tiny hands with exactly two visible clawed fingers when visible",
                "no third finger on either hand",
            ],
            "rejectIf": [
                "three or more fingers on a visible hand",
                "four fingers",
                "spread hand with three claws",
                "long grasping arms",
                "forelimbs reaching below the belly",
                "human-like hands",
                "extra fingers",
                "missing both forelimbs when the torso is visible",
            ],
        },
    },
    "spinosaurus-aegyptiacus": {
        "scientificName": "Spinosaurus aegyptiacus",
        "period": "Late Cretaceous",
        "region": "North African river delta",
        "visualTraits": [
            "large semi-aquatic spinosaurid theropod",
            "long narrow crocodile-like snout with conical teeth",
            "very tall obvious continuous dorsal sail rising high over the back",
            "the dorsal sail is the dominant silhouette feature",
            "long low body profile",
            "powerful forelimbs with large claws held off the ground",
            "two strong hind legs with broad grounded feet",
            "long deep tail for swimming",
        ],
        "surface": "intact natural skin, fine pebbled scales, subtle aquatic countershading",
        "anatomyRules": {
            "mustHave": [
                "long narrow crocodile-like skull",
                "very tall continuous dorsal sail on the back",
                "dorsal sail must be clearly visible above the torso silhouette",
                "large theropod body",
                "two grounded hind legs",
                "long deep tail",
                "forelimbs visible but not weight-bearing",
                "riverbank or delta setting without hiding the feet",
            ],
            "rejectIf": [
                "Tyrannosaurus-like deep blocky skull",
                "Allosaurus-like short skull",
                "missing dorsal sail",
                "low smooth back with no sail",
                "small ridge instead of a tall sail",
                "separate stegosaurus plates instead of a sail",
                "quadrupedal crocodile body",
                "all four limbs walking like a crocodile",
                "tail or feet hidden by water",
                "fish-only scene with no full dinosaur body",
                "extra sail",
                "horns or frill",
            ],
        },
    },
    "parasaurolophus-walkeri": {
        "scientificName": "Parasaurolophus walkeri",
        "period": "Late Cretaceous",
        "region": "North American coastal plain",
        "visualTraits": [
            "large hadrosaurid herbivore",
            "long backward-curving tube crest extending from the skull",
            "the head crest is a rigid bony tube, not feathers",
            "duck-billed herbivore snout",
            "deep but graceful body",
            "long stiff balancing tail",
            "strong hind limbs and smaller forelimbs",
            "facultative quadrupedal walking pose with all feet visible",
        ],
        "surface": "intact natural skin, fine pebbled scales, muted banding",
        "anatomyRules": {
            "mustHave": [
                "single long backward-curving head crest",
                "rigid tubular skull crest longer than the skull",
                "duck-billed hadrosaur head",
                "herbivore body with no sharp predator teeth",
                "long tail fully visible",
                "four limbs visible with smaller forelimbs than hind limbs",
                "full side-profile body",
            ],
            "rejectIf": [
                "no crest",
                "short horn instead of long tube crest",
                "crest points forward",
                "ceratopsian frill",
                "theropod predator skull",
                "sharp exposed carnivore teeth",
                "sauropod long neck",
                "stegosaurus plates",
                "ankylosaur armor",
                "tail cropped or hidden",
                "bird body",
                "goose body",
                "swan body",
                "ostrich body",
                "feathered bird",
                "wings",
                "beak like a modern bird",
            ],
        },
    },
    "pachycephalosaurus-wyomingensis": {
        "scientificName": "Pachycephalosaurus wyomingensis",
        "period": "Late Cretaceous",
        "region": "North American upland floodplain",
        "visualTraits": [
            "medium bipedal pachycephalosaurid ornithischian",
            "very thick rounded skull dome that dominates the head silhouette",
            "high bald bony dome on top of the skull",
            "small blunt herbivore beak",
            "short skull spikes and knobs around the back of the head",
            "compact torso",
            "small forelimbs",
            "long balancing tail",
            "two strong hind legs",
        ],
        "surface": "intact natural skin, fine pebbled scales, subtle head knobs",
        "anatomyRules": {
            "mustHave": [
                "large rounded skull dome",
                "high thick bony dome clearly visible in side profile",
                "small herbivore beak with no predator teeth",
                "short head knobs or small spikes around the rear skull",
                "bipedal ornithischian body",
                "small forelimbs",
                "long balancing tail",
                "two grounded hind legs",
            ],
            "rejectIf": [
                "flat skull with no dome",
                "ordinary hadrosaur head with no dome",
                "long duck-billed snout",
                "ceratopsian horns or frill",
                "theropod predator skull",
                "sharp exposed carnivore teeth",
                "Tyrannosaurus-like giant head",
                "quadrupedal stance",
                "stegosaurus plates",
                "ankylosaur armor",
                "tail hidden or cropped",
            ],
        },
    },
    "triceratops-horridus": {
        "scientificName": "Triceratops horridus",
        "period": "Late Cretaceous",
        "region": "North American coastal plain",
            "visualTraits": [
                "exactly three facial horns: two long brow horns and one short nasal horn",
                "large solid shield-like neck frill attached behind the skull, not on the back",
                "parrot-like beak",
                "closed mouth side-profile head",
                "sturdy quadrupedal ceratopsian dinosaur body with clawed toes",
            ],
        "surface": "intact natural skin, subtle scales",
        "anatomyRules": {
            "facialHorns": 3,
            "mustHave": [
                "exactly two brow horns and exactly one nasal horn",
                "large solid shield-like neck frill attached to the back of the skull",
                "closed mouth with a beak, no teeth visible",
                "sturdy quadrupedal ceratopsian stance",
                "dinosaur feet with visible toes or blunt claws, not hoofed mammal feet",
            ],
            "rejectIf": [
                "extra facial horns beyond three",
                "four or more horns",
                "missing nasal horn",
                "missing brow horns",
                "open roaring mouth",
                "visible sharp teeth",
                "frill growing from the back",
                "dorsal sail",
                "spines or plates along the back",
                "rhinoceros body",
                "rhinoceros-like shoulder hump",
                "mammal torso or mammal leg proportions",
                "mammal hooves",
                "hoof-like feet",
                "theropod body plan",
                "bipedal stance",
            ],
        },
    },
    "stegosaurus-stenops": {
        "scientificName": "Stegosaurus stenops",
        "period": "Late Jurassic",
        "region": "North American floodplain",
        "visualTraits": [
            "many separate broad angular bony dorsal plates, not a few giant triangular sails",
            "two staggered rows of dorsal plates alternating left and right along the back",
            "left-facing full side-profile view where the alternating plates overlap along the back",
            "largest plates over the hips and mid-back, smaller plates toward the neck and tail base",
            "matte diamond and kite-shaped bony plates embedded into the back with angular shoulders, blunt tips, and rough scute texture, not oval back fins, rounded petals, or plant leaves",
            "visible separation and sky/background gaps between individual dorsal plates rather than a fused scalloped fan",
            "smooth tail shaft after the hip plates, with no small dorsal spines along the tail",
            "small low head",
            "arched quadrupedal body",
            "tail end in frame with four tail spikes on the thagomizer",
        ],
        "surface": "intact natural skin, subtle scales",
        "anatomyRules": {
            "mustHave": [
                "many separate individual dorsal plates",
                "two staggered rows of dorsal plates",
                "alternating left-right plate arrangement visible from a side profile",
                "full side-profile body, not a rear view",
                "varied plate sizes with smaller plates near the neck and tail base",
                "broad angular diamond-shaped bony dorsal plates embedded into the back rather than oval fins, rounded petals, needle spines, plant leaves, or leaf veins",
                "visible gaps between individual dorsal plates instead of a fused scalloped fan",
                "smooth tail shaft between the last dorsal plate and the tail-tip spikes",
                "four long tail spikes",
                "tail end visible in frame",
                "only one head at the front of the body",
                "tail spikes are not a second head",
                "small head held low",
                "quadrupedal stance",
            ],
            "rejectIf": [
                "missing dorsal plates",
                "single smooth sail instead of separate plates",
                "five huge triangular mountain plates",
                "few giant triangular sails",
                "roof-like row of identical triangles",
                "single centered sawblade crest",
                "rounded oval back fins",
                "rounded flower-petal plates",
                "soft petal-like dorsal plates",
                "fused scalloped fan of dorsal plates",
                "one continuous arched plate row with only painted seam lines",
                "soft hump-like plates fused into the body",
                "thin comb-like spines instead of broad plates",
                "plant leaves or green foliage used as dorsal plates",
                "leaf veins on the dorsal plates",
                "needle spines running along the tail shaft",
                "continuous bristly crest along the tail",
                "tail covered with many small spikes",
                "rear view",
                "back view",
                "symmetrical view from behind",
                "body rotated toward the viewer to show both flanks",
                "missing tail spikes",
                "tail cropped before the thagomizer",
                "second head on the tail",
                "eye or face on the tail",
                "horned head instead of tail spikes",
                "ankylosaur armor shell",
                "theropod body plan",
                "bipedal stance",
            ],
        },
    },
    "velociraptor-mongoliensis": {
        "scientificName": "Velociraptor mongoliensis",
        "period": "Late Cretaceous",
        "region": "Mongolian desert",
        "visualTraits": [
            "small turkey-sized feathered dromaeosaurid body",
            "dense downy feather coat across the torso and neck",
            "long stiff balancing tail",
            "large sickle claw on the second toe",
            "visible folded feathered forelimbs held close against the ribs",
            "short wing-like feathered arms folded downward, not spread for flight",
            "slender low theropod posture",
            "toothed narrow dinosaur snout, not a bird beak",
        ],
        "surface": "dense downy feathered body, folded feathered forelimbs, natural layered feather texture",
        "anatomyRules": {
            "mustHave": [
                "dense feathers covering the torso, neck, hips, and arms",
                "visible folded feathered forelimbs held close to the torso",
                "bird-like feather coverage on the torso and arms",
                "short wing-like arms folded downward along the body",
                "toothed narrow dinosaur snout",
                "large sickle claw on each second toe",
                "small turkey-sized animal scale, not human-sized",
                "long stiff tail",
            ],
            "rejectIf": [
                "giant movie raptor proportions",
                "ostrich-like ornithomimid body",
                "long ostrich neck",
                "bird beak",
                "toothless beak",
                "flying bird body",
                "large spread bird wings",
                "eagle wings",
                "crane wings",
                "flight feathers spread for flying",
                "crane-like body",
                "heron-like body",
                "roadrunner-like body",
                "scaly naked arms",
                "bald naked arms",
                "smooth naked skin",
                "wrinkled scaleless naked torso",
                "tyrannosaur-like scaly body",
                "unfeathered body",
                "porcupine quills",
                "spines along the back",
                "large dorsal spikes",
                "mohawk crest",
                "pangolin scales",
                "armored scale rows",
                "missing sickle claw",
                "oversized tyrannosaur head",
                "human-sized monster",
            ],
        },
    },
    "brachiosaurus-altithorax": {
        "scientificName": "Brachiosaurus altithorax",
        "period": "Late Jurassic",
        "region": "North American woodland",
        "visualTraits": [
            "very long upright neck",
            "small narrow herbivore sauropod head high above the shoulders",
            "subtle raised nasal arch on the skull",
            "front limbs visibly longer and taller than hind limbs",
            "high shoulders sloping down toward the hips",
            "shorter tail than a diplodocid sauropod",
            "camera pulled back so the full tail tip and all feet are visible",
            "massive quadrupedal sauropod body",
        ],
        "surface": "intact natural skin, subtle scales",
        "anatomyRules": {
            "mustHave": [
                "front limbs longer than hind limbs",
                "high shoulder profile",
                "body slopes downward from shoulders to hips",
                "very long upright neck",
                "small herbivore head with no predator teeth",
                "shorter tail, not a whip tail",
                "entire tail tip visible inside the frame",
                "all four feet visible inside the frame",
                "quadrupedal stance",
                "side profile view",
            ],
            "rejectIf": [
                "short neck",
                "low diplodocid body plan",
                "Apatosaurus-like low neck",
                "Diplodocus-like whip tail",
                "front and hind limbs equal height",
                "hips higher than shoulders",
                "theropod body plan",
                "bipedal stance",
                "predator skull",
                "crocodile-like flat head",
                "large toothy mouth",
                "visible predator teeth",
                "tail dragging on the ground",
                "rear view",
                "back view",
            ],
        },
    },
    "ankylosaurus-magniventris": {
        "scientificName": "Ankylosaurus magniventris",
        "period": "Late Cretaceous",
        "region": "North American floodplain",
        "visualTraits": [
            "low wide armored body",
            "low rounded bony osteoderms embedded across the back",
            "large heavy tail club at the end of the tail",
            "broad triangular armored skull held low",
            "sturdy quadrupedal stance",
        ],
        "surface": "bony armor plates over intact natural skin",
        "anatomyRules": {
            "mustHave": [
                "low wide armored body",
                "flat low back profile",
                "low rounded osteoderms embedded across the back",
                "visible bony armor knobs, not tall plates",
                "large solid bony tail club visible in frame",
                "tail club fully attached to the tail and visible inside the frame",
                "tail club is a broad rounded bone knob, not a spiked mace",
                "broad triangular armored skull",
                "quadrupedal stance",
            ],
            "rejectIf": [
                "missing tail club",
                "tail cropped before the club",
                "detached tail club",
                "floating oval tail club",
                "spiked mace tail club",
                "many spikes on the tail club",
                "fluffy tail club",
                "tail club replaced by a thin tail",
                "smooth unarmored back",
                "tall dorsal spikes",
                "spines along the back",
                "sharp vertical back spikes",
                "tall dorsal plates",
                "raised stegosaurus plates",
                "vertical back plates",
                "stegosaurus-like silhouette",
                "turtle shell",
                "tortoise shell",
                "blue shell",
                "theropod body plan",
                "bipedal stance",
                "long sauropod neck",
            ],
        },
    },
}


NEGATIVE_PROMPT = (
    "text, labels, captions, writing, watermark, logo, signature, artist signature, artist name, initials, "
    "tiny letters, corner text, bottom right mark, copyright mark, border, multiple dinosaurs, two animals, "
    "duplicate dinosaur, baby dinosaur, herd, skeleton, exposed bones, visible ribs, rib cage, skull-only, "
    "fossil, xray, anatomical diagram, scientific diagram, blueprint, chart, parchment, paper background, "
    "museum skeleton, museum display, movie monster, fantasy dragon, kaiju, toy, plastic, cartoon, anime, "
    "roaring monster, attacking pose, dramatic sunset, cinematic orange lighting, horror lighting, "
    "incorrect limb count, extra head, extra tail, extra arms, extra fingers, missing feet, broken feet, "
    "human-like hands, mangled hands, cropped body, "
    "cropped tail, cropped feet, out of frame, blurry, monochrome, grayscale, "
    "sepia, washed out colors, oversaturated neon colors, color cast, heavy fog, bloom, human rider, saddle"
)


def build_prompt(taxon_id):
    dino = DINOSAURS[taxon_id]
    traits = ", ".join(dino["visualTraits"])
    anatomy_rules = dino.get("anatomyRules", {})
    anatomy_must = ", ".join(anatomy_rules.get("mustHave", []))
    anatomy_negative = ", ".join(anatomy_rules.get("rejectIf", []))
    negative = f"{NEGATIVE_PROMPT}, {anatomy_negative}" if anatomy_negative else NEGATIVE_PROMPT
    surface = dino.get("surface", "intact natural skin, subtle scales")
    positive = (
        "clean digital paleoart, modern dinosaur encyclopedia quality, non-signed image, no artist mark, "
        f"professional natural history reconstruction, single adult {dino['scientificName']}, only one animal, "
        "full body lateral side view, entire animal visible with clear margins, calm standing or slow walking pose, "
        f"{dino['period']}, {dino['region']} environment, {traits}, robust plausible body, {surface}, "
        f"{anatomy_must}, believable soft tissue, open habitat, sparse vegetation, clean daylight, balanced white balance, "
        "realistic earth tones, natural contrast, high fidelity but restrained detail, clean empty corners, "
        "no text, no logo, no watermark"
    )
    anatomy_checklist = [
        f"anatomy must-have: {item}" for item in anatomy_rules.get("mustHave", [])
    ] + [f"reject if: {item}" for item in anatomy_rules.get("rejectIf", [])]
    return {
        "taxonId": taxon_id,
        "positivePrompt": positive,
        "negativePrompt": negative,
        "visualTraits": dino["visualTraits"],
        "anatomyRules": anatomy_rules,
        "reviewChecklist": [
            "full body visible",
            "no text or watermark",
            "limb count matches the taxon",
            "silhouette matches the taxon group",
            *anatomy_checklist,
        ],
    }


if __name__ == "__main__":
    output = build_prompt("tyrannosaurus-rex")
    out_path = Path(__file__).resolve().parents[1] / "sample_prompt.json"
    out_path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(output, ensure_ascii=False, indent=2))
